# <center> Engenharia de Prompt - ChatGPT aplicado ao Direito </center>

<div style="text-align: right">Versão 2023-05-05</div>

- [**Vídeos deste tutorial no Youtube**](https://youtube.com/playlist?list=PLwEXPYCX6dlJSGVaaJ5LPFQcTKwKkHcYR)
- Legal Prompt Engineering (Prompt Engineering for Law)
  - Key-words: initial application, case outcome, legal documents, law, legal advice, appeal, justice, judge, legal decision, machine learning, artificial intelligence
- Author: [André Lage Freitas](https://linkedin.com/in/lage)
  - Associate Professor at Universidade Federal de Alagoas (UFAL)
  - PhD in Computer Science from the _Institut National des Sciences Appliquées de Rennes_ (France)
- Some parts of the source code used here come from:
  - [DeepLearningAI: ChatGPT Prompt Engineering for Developers](https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers/)
  - Image Credits: Isa Fulford and Andrew Ng




### A. Prompt Engineering: Visão geral 

1. Seja claro e preciso
1. Interaja até encontrar um prompt adequado
1. Use exemplos
1. Divida um problema complexo em subproblemas
1. Guarde seus prompts bons
1. Teste seus prompts com outras entradas
1. Peça para outras pessoas testarem seus prompts

<img src="prompt-overview.png"  width="450" align="left">

### B. Como executar os prompts desse material

1. **Copiar e colar no [ChatGPT](https://chat.openai.com/)** o prompt formatado
2. Abrir esse arquivo `.ipynb` no [Google Colab](https://colab.research.google.com/)

In [39]:
# configurando openai API
import os
import openai
openai.api_key = os.getenv("OPENAI_API_KEY")

# função para simplicar a chamada da API
# def get_completion(prompt, model="gpt-4"): 
def get_completion(prompt, model="gpt-3.5-turbo"): 
    messages = [{"role": "user", "content": prompt}]
    response = openai.ChatCompletion.create(
        model=model,
        messages=messages,
        temperature=0, 
    )
    return response.choices[0].message["content"]

# para formatar a saída em Markdown
from IPython.display import display, Markdown

def print_prompt_answer(prompt):
    display(Markdown("### Prompt"))
    print(prompt)
#     display(Markdown(prompt))    
    response = get_completion(prompt)
    display(Markdown("### Resposta"))
    display(Markdown(response))
    print(response)

## 1. Extração de informações em documentos jurídicos

- **Objetivo**: extrair citações de normas jurídicas.

Entidades são palavras ou sequências de palavras em um texto que representam entidades do mundo real, como pessoas, organizações, localizações, datas, quantidades e outros conceitos específicos. Extrair entidades é identificar e classificar essas entidades em categorias predefinidas.

Por exemplo, vamos os nomes de entidades da [LAI (DECRETO Nº 7.724, DE 16 DE MAIO DE 2012)](https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2012/decreto/d7724.htm).


In [40]:
parte_da_lai = """
 DECRETO Nº 7.724, DE 16 DE MAIO DE 2012
Vigência 	

Regulamenta a Lei nº 12.527, de 18 de novembro de 2011, que dispõe sobre o acesso a informações previsto no inciso XXXIII do caput do art. 5º , no inciso II do § 3º do art. 37 e no § 2º do art. 216 da Constituição.

A PRESIDENTA DA REPÚBLICA, no uso das atribuições que lhe confere o art. 84, caput, incisos IV e VI, alínea “a”, da Constituição, e tendo em vista o disposto na Lei nº 12.527, de 18 de novembro de 2011,

DECRETA:

CAPÍTULO I

DISPOSIÇÕES GERAIS

Art. 1º Este Decreto regulamenta, no âmbito do Poder Executivo federal, os procedimentos para a garantia do acesso à informação e para a classificação de informações sob restrição de acesso, observados grau e prazo de sigilo, conforme o disposto na Lei nº 12.527, de 18 de novembro de 2011, que dispõe sobre o acesso a informações previsto no inciso XXXIII do caput do art. 5º , no inciso II do § 3º do art. 37 e no § 2º do art. 216 da Constituição.

Art. 2º Os órgãos e as entidades do Poder Executivo federal assegurarão, às pessoas naturais e jurídicas, o direito de acesso à informação, que será proporcionado mediante procedimentos objetivos e ágeis, de forma transparente, clara e em linguagem de fácil compreensão, observados os princípios da administração pública e as diretrizes previstas na Lei nº 12.527, de 2011.

Art. 3º Para os efeitos deste Decreto, considera-se:

I - informação - dados, processados ou não, que podem ser utilizados para produção e transmissão de conhecimento, contidos em qualquer meio, suporte ou formato;

II - dados processados - dados submetidos a qualquer operação ou tratamento por meio de processamento eletrônico ou por meio automatizado com o emprego de tecnologia da informação;

III - documento - unidade de registro de informações, qualquer que seja o suporte ou formato;

IV - informação sigilosa - informação submetida temporariamente à restrição de acesso público em razão de sua imprescindibilidade para a segurança da sociedade e do Estado, e aquelas abrangidas pelas demais hipóteses legais de sigilo;

V - informação pessoal - informação relacionada à pessoa natural identificada ou identificável, relativa à intimidade, vida privada, honra e imagem;

VI - tratamento da informação - conjunto de ações referentes à produção, recepção, classificação, utilização, acesso, reprodução, transporte, transmissão, distribuição, arquivamento, armazenamento, eliminação, avaliação, destinação ou controle da informação;

VII - disponibilidade - qualidade da informação que pode ser conhecida e utilizada por indivíduos, equipamentos ou sistemas autorizados;

VIII - autenticidade - qualidade da informação que tenha sido produzida, expedida, recebida ou modificada por determinado indivíduo, equipamento ou sistema;

IX - integridade - qualidade da informação não modificada, inclusive quanto à origem, trânsito e destino;

X - primariedade - qualidade da informação coletada na fonte, com o máximo de detalhamento possível, sem modificações;

XI - informação atualizada - informação que reúne os dados mais recentes sobre o tema, de acordo com sua natureza, com os prazos previstos em normas específicas ou conforme a periodicidade estabelecida nos sistemas informatizados que a organizam; e

XII - documento preparatório - documento formal utilizado como fundamento da tomada de decisão ou de ato administrativo, a exemplo de pareceres e notas técnicas.

Art. 4º A busca e o fornecimento da informação são gratuitos, ressalvada a cobrança do valor referente ao custo dos serviços e dos materiais utilizados, tais como reprodução de documentos, mídias digitais e postagem.

Parágrafo único. Está isento de ressarcir os custos dos serviços e dos materiais utilizados aquele cuja situação econômica não lhe permita fazê-lo sem prejuízo do sustento próprio ou da família, declarada nos termos da Lei nº 7.115, de 29 de agosto de 1983.

CAPÍTULO II

DA ABRANGÊNCIA

Art. 5º Sujeitam-se ao disposto neste Decreto os órgãos da administração direta, as autarquias, as fundações públicas, as empresas públicas, as sociedades de economia mista e as demais entidades controladas direta ou indiretamente pela União.

§ 1º A divulgação de informações de empresas públicas, sociedade de economia mista e demais entidades controladas pela União que atuem em regime de concorrência, sujeitas ao disposto no art. 173 da Constituição, estará submetida às normas pertinentes da Comissão de Valores Mobiliários, a fim de assegurar sua competitividade, governança corporativa e, quando houver, os interesses de acionistas minoritários.

§ 2º Não se sujeitam ao disposto neste Decreto as informações relativas à atividade empresarial de pessoas físicas ou jurídicas de direito privado obtidas pelo Banco Central do Brasil, pelas agências reguladoras ou por outros órgãos ou entidades no exercício de atividade de controle, regulação e supervisão da atividade econômica cuja divulgação possa representar vantagem competitiva a outros agentes econômicos.

Art. 6º O acesso à informação disciplinado neste Decreto não se aplica:

I - às hipóteses de sigilo previstas na legislação, como fiscal, bancário, de operações e serviços no mercado de capitais, comercial, profissional, industrial e segredo de justiça; e

II - às informações referentes a projetos de pesquisa e desenvolvimento científicos ou tecnológicos cujo sigilo seja imprescindível à segurança da sociedade e do Estado, na forma do §1º do art. 7º da Lei nº 12.527, de 2011. 
"""

In [41]:
prompt = f"""
Sua tarefa é extratir nomes de entidades de uma lei brasileira. \
A partir da lei abaixo, delimitada por "###", extraia todas as \
entidades e indique qual o tipo de entidade para cada entidade \
encontrada. Organize os dados em uma tabela. \


###{parte_da_lai}###
"""

print_prompt_answer(prompt)

### Prompt


Sua tarefa é extratir nomes de entidades de uma lei brasileira. A partir da lei abaixo, delimitada por "###", extraia todas as entidades e indique qual o tipo de entidade para cada entidade encontrada. Organize os dados em uma tabela. 

###
 DECRETO Nº 7.724, DE 16 DE MAIO DE 2012
Vigência 	

Regulamenta a Lei nº 12.527, de 18 de novembro de 2011, que dispõe sobre o acesso a informações previsto no inciso XXXIII do caput do art. 5º , no inciso II do § 3º do art. 37 e no § 2º do art. 216 da Constituição.

A PRESIDENTA DA REPÚBLICA, no uso das atribuições que lhe confere o art. 84, caput, incisos IV e VI, alínea “a”, da Constituição, e tendo em vista o disposto na Lei nº 12.527, de 18 de novembro de 2011,

DECRETA:

CAPÍTULO I

DISPOSIÇÕES GERAIS

Art. 1º Este Decreto regulamenta, no âmbito do Poder Executivo federal, os procedimentos para a garantia do acesso à informação e para a classificação de informações sob restrição de acesso, observados grau e prazo de sigilo, conforme o dispos

### Resposta

| Entidade | Tipo de Entidade |
| --- | --- |
| Lei nº 12.527 | Lei |
| Constituição | Documento |
| Poder Executivo federal | Órgão |
| Pessoas naturais | Pessoa |
| Pessoas jurídicas | Pessoa |
| Princípios da administração pública | Diretriz |
| Órgãos e entidades do Poder Executivo federal | Órgão/Entidade |
| Informação | Dado |
| Dados processados | Dado |
| Documento | Unidade de registro |
| Informação sigilosa | Informação |
| Segurança da sociedade e do Estado | Conceito |
| Hipóteses legais de sigilo | Conceito |
| Informação pessoal | Informação |
| Tratamento da informação | Ação |
| Disponibilidade | Qualidade |
| Autenticidade | Qualidade |
| Integridade | Qualidade |
| Primariedade | Qualidade |
| Informação atualizada | Informação |
| Documento preparatório | Documento |
| Serviços e materiais utilizados | Custo |
| Lei nº 7.115 | Lei |
| Administração direta | Órgão |
| Autarquias | Entidade |
| Fundações públicas | Entidade |
| Empresas públicas | Entidade |
| Sociedades de economia mista | Entidade |
| União | Entidade |
| Regime de concorrência | Conceito |
| Art. 173 da Constituição | Artigo |
| Comissão de Valores Mobiliários | Órgão |
| Acionistas minoritários | Pessoa |
| Banco Central do Brasil | Órgão |
| Agências reguladoras | Órgão |
| Controle, regulação e supervisão da atividade econômica | Conceito |
| Atividade empresarial de pessoas físicas ou jurídicas de direito privado | Conceito |
| Projetos de pesquisa e desenvolvimento científicos ou tecnológicos | Informação |

| Entidade | Tipo de Entidade |
| --- | --- |
| Lei nº 12.527 | Lei |
| Constituição | Documento |
| Poder Executivo federal | Órgão |
| Pessoas naturais | Pessoa |
| Pessoas jurídicas | Pessoa |
| Princípios da administração pública | Diretriz |
| Órgãos e entidades do Poder Executivo federal | Órgão/Entidade |
| Informação | Dado |
| Dados processados | Dado |
| Documento | Unidade de registro |
| Informação sigilosa | Informação |
| Segurança da sociedade e do Estado | Conceito |
| Hipóteses legais de sigilo | Conceito |
| Informação pessoal | Informação |
| Tratamento da informação | Ação |
| Disponibilidade | Qualidade |
| Autenticidade | Qualidade |
| Integridade | Qualidade |
| Primariedade | Qualidade |
| Informação atualizada | Informação |
| Documento preparatório | Documento |
| Serviços e materiais utilizados | Custo |
| Lei nº 7.115 | Lei |
| Administração direta | Órgão |
| Autarquias | Entidade |
| Fundações públicas | Entidade |
| Empresas públicas | Entidade |
| Socied

- Vamos pedir para ser mais conciso

In [42]:
prompt = f"""
Sua tarefa é extratir nomes de entidades de uma lei brasileira. \
A partir da lei abaixo, delimitada por "###", extraia todas as \
entidades e indique qual o tipo de entidade para cada entidade \
encontrada. Organize os dados em uma tabela. \

Seja conciso e considere apenas as principais entidades. \

###{parte_da_lai}###
"""

print_prompt_answer(prompt)

### Prompt


Sua tarefa é extratir nomes de entidades de uma lei brasileira. A partir da lei abaixo, delimitada por "###", extraia todas as entidades e indique qual o tipo de entidade para cada entidade encontrada. Organize os dados em uma tabela. 
Seja conciso e considere apenas as principais entidades. 
###
 DECRETO Nº 7.724, DE 16 DE MAIO DE 2012
Vigência 	

Regulamenta a Lei nº 12.527, de 18 de novembro de 2011, que dispõe sobre o acesso a informações previsto no inciso XXXIII do caput do art. 5º , no inciso II do § 3º do art. 37 e no § 2º do art. 216 da Constituição.

A PRESIDENTA DA REPÚBLICA, no uso das atribuições que lhe confere o art. 84, caput, incisos IV e VI, alínea “a”, da Constituição, e tendo em vista o disposto na Lei nº 12.527, de 18 de novembro de 2011,

DECRETA:

CAPÍTULO I

DISPOSIÇÕES GERAIS

Art. 1º Este Decreto regulamenta, no âmbito do Poder Executivo federal, os procedimentos para a garantia do acesso à informação e para a classificação de informações sob restrição de ace

### Resposta

| Entidade | Tipo de Entidade |
| --- | --- |
| Lei nº 12.527 | Lei |
| Constituição | Documento |
| Poder Executivo federal | Órgão |
| Pessoa natural | Categoria |
| Pessoa jurídica | Categoria |
| Princípios da administração pública | Diretrizes |
| Órgãos e entidades do Poder Executivo federal | Órgãos e entidades |
| Informação | Dado |
| Dados processados | Dado |
| Documento | Unidade de registro |
| Informação sigilosa | Informação |
| Segurança da sociedade e do Estado | Categoria |
| Informação pessoal | Informação |
| Tratamento da informação | Ação |
| Disponibilidade | Qualidade |
| Autenticidade | Qualidade |
| Integridade | Qualidade |
| Primariedade | Qualidade |
| Informação atualizada | Informação |
| Documento preparatório | Documento |
| Serviços e materiais utilizados | Custos |
| Lei nº 7.115 | Lei |
| Administração direta | Órgão |
| Autarquias | Órgão |
| Fundações públicas | Órgão |
| Empresas públicas | Órgão |
| Sociedades de economia mista | Órgão |
| União | Entidade |
| Comissão de Valores Mobiliários | Órgão |
| Acionistas minoritários | Categoria |
| Banco Central do Brasil | Órgão |
| Agências reguladoras | Órgão |
| Controle, regulação e supervisão da atividade econômica | Categoria |
| Atividade empresarial de pessoas físicas ou jurídicas de direito privado | Categoria |
| Projetos de pesquisa e desenvolvimento científicos ou tecnológicos | Categoria |

| Entidade | Tipo de Entidade |
| --- | --- |
| Lei nº 12.527 | Lei |
| Constituição | Documento |
| Poder Executivo federal | Órgão |
| Pessoa natural | Categoria |
| Pessoa jurídica | Categoria |
| Princípios da administração pública | Diretrizes |
| Órgãos e entidades do Poder Executivo federal | Órgãos e entidades |
| Informação | Dado |
| Dados processados | Dado |
| Documento | Unidade de registro |
| Informação sigilosa | Informação |
| Segurança da sociedade e do Estado | Categoria |
| Informação pessoal | Informação |
| Tratamento da informação | Ação |
| Disponibilidade | Qualidade |
| Autenticidade | Qualidade |
| Integridade | Qualidade |
| Primariedade | Qualidade |
| Informação atualizada | Informação |
| Documento preparatório | Documento |
| Serviços e materiais utilizados | Custos |
| Lei nº 7.115 | Lei |
| Administração direta | Órgão |
| Autarquias | Órgão |
| Fundações públicas | Órgão |
| Empresas públicas | Órgão |
| Sociedades de economia mista | Órgão |
| União 

- Ainda não ficou bom
- Vamos pedir para focar apenas em leis

In [43]:
prompt = f"""
Sua tarefa é extratir nomes de entidades de uma lei brasileira. \
A partir da lei abaixo, delimitada por "###", extraia todas as \
entidades e indique qual o tipo de entidade para cada entidade \
encontrada. Organize os dados em uma tabela. \

Considere apenas entidades do tipo "Lei". \

###{parte_da_lai}###
"""

print_prompt_answer(prompt)


### Prompt


Sua tarefa é extratir nomes de entidades de uma lei brasileira. A partir da lei abaixo, delimitada por "###", extraia todas as entidades e indique qual o tipo de entidade para cada entidade encontrada. Organize os dados em uma tabela. 
Considere apenas entidades do tipo "Lei". 
###
 DECRETO Nº 7.724, DE 16 DE MAIO DE 2012
Vigência 	

Regulamenta a Lei nº 12.527, de 18 de novembro de 2011, que dispõe sobre o acesso a informações previsto no inciso XXXIII do caput do art. 5º , no inciso II do § 3º do art. 37 e no § 2º do art. 216 da Constituição.

A PRESIDENTA DA REPÚBLICA, no uso das atribuições que lhe confere o art. 84, caput, incisos IV e VI, alínea “a”, da Constituição, e tendo em vista o disposto na Lei nº 12.527, de 18 de novembro de 2011,

DECRETA:

CAPÍTULO I

DISPOSIÇÕES GERAIS

Art. 1º Este Decreto regulamenta, no âmbito do Poder Executivo federal, os procedimentos para a garantia do acesso à informação e para a classificação de informações sob restrição de acesso, observados

### Resposta

| Entidade | Tipo de Entidade |
| --- | --- |
| Lei nº 12.527 | Lei |
| Constituição | Lei |
| Poder Executivo federal | Órgão |
| Administração direta | Órgão |
| Autarquias | Órgão |
| Fundações públicas | Órgão |
| Empresas públicas | Órgão |
| Sociedades de economia mista | Órgão |
| União | Órgão | 
| Comissão de Valores Mobiliários | Órgão |
| Banco Central do Brasil | Órgão |
| Agências reguladoras | Órgão |

| Entidade | Tipo de Entidade |
| --- | --- |
| Lei nº 12.527 | Lei |
| Constituição | Lei |
| Poder Executivo federal | Órgão |
| Administração direta | Órgão |
| Autarquias | Órgão |
| Fundações públicas | Órgão |
| Empresas públicas | Órgão |
| Sociedades de economia mista | Órgão |
| União | Órgão | 
| Comissão de Valores Mobiliários | Órgão |
| Banco Central do Brasil | Órgão |
| Agências reguladoras | Órgão |


- Ainda não ficou bom..
- Vamos usar outro nome: normas jurídicas

In [44]:
# ao invés de dizer para excluir o tipo "Órgão", vamos mudar a abordagem
prompt = f"""
Quais normas jurídicas são citadas pelo documento jurídico delimitado por "###"? \

###{parte_da_lai}###
"""
print_prompt_answer(prompt)

### Prompt


Quais normas jurídicas são citadas pelo documento jurídico delimitado por "###"? 
###
 DECRETO Nº 7.724, DE 16 DE MAIO DE 2012
Vigência 	

Regulamenta a Lei nº 12.527, de 18 de novembro de 2011, que dispõe sobre o acesso a informações previsto no inciso XXXIII do caput do art. 5º , no inciso II do § 3º do art. 37 e no § 2º do art. 216 da Constituição.

A PRESIDENTA DA REPÚBLICA, no uso das atribuições que lhe confere o art. 84, caput, incisos IV e VI, alínea “a”, da Constituição, e tendo em vista o disposto na Lei nº 12.527, de 18 de novembro de 2011,

DECRETA:

CAPÍTULO I

DISPOSIÇÕES GERAIS

Art. 1º Este Decreto regulamenta, no âmbito do Poder Executivo federal, os procedimentos para a garantia do acesso à informação e para a classificação de informações sob restrição de acesso, observados grau e prazo de sigilo, conforme o disposto na Lei nº 12.527, de 18 de novembro de 2011, que dispõe sobre o acesso a informações previsto no inciso XXXIII do caput do art. 5º , no inciso II do § 3

### Resposta

As normas jurídicas citadas pelo documento jurídico são a Constituição Federal, a Lei nº 12.527/2011 e a Lei nº 7.115/1983.

As normas jurídicas citadas pelo documento jurídico são a Constituição Federal, a Lei nº 12.527/2011 e a Lei nº 7.115/1983.


- Melhorou!
- Vamos agora pedir para formatar a saída em uma tabela

In [45]:
prompt = f"""
Quais normas jurídicas são citadas pelo documento jurídico delimitado por "###"? \

Organize os dados em uma tabela da seguinte forma: \
- coluna 1: nome da norma \
- coluna 2: artigo da norma que foi citada. \
- coluna 3: breve explicação do conteúdo da coluna 2, ou seja, do artigo da norma que foi citada. \

###{parte_da_lai}###
"""
print_prompt_answer(prompt)

### Prompt


Quais normas jurídicas são citadas pelo documento jurídico delimitado por "###"? 
Organize os dados em uma tabela da seguinte forma: - coluna 1: nome da norma - coluna 2: artigo da norma que foi citada. - coluna 3: breve explicação do conteúdo da coluna 2, ou seja, do artigo da norma que foi citada. 
###
 DECRETO Nº 7.724, DE 16 DE MAIO DE 2012
Vigência 	

Regulamenta a Lei nº 12.527, de 18 de novembro de 2011, que dispõe sobre o acesso a informações previsto no inciso XXXIII do caput do art. 5º , no inciso II do § 3º do art. 37 e no § 2º do art. 216 da Constituição.

A PRESIDENTA DA REPÚBLICA, no uso das atribuições que lhe confere o art. 84, caput, incisos IV e VI, alínea “a”, da Constituição, e tendo em vista o disposto na Lei nº 12.527, de 18 de novembro de 2011,

DECRETA:

CAPÍTULO I

DISPOSIÇÕES GERAIS

Art. 1º Este Decreto regulamenta, no âmbito do Poder Executivo federal, os procedimentos para a garantia do acesso à informação e para a classificação de informações sob restriçã

### Resposta

| Nome da norma | Artigo citado | Breve explicação do conteúdo do artigo |
| --- | --- | --- |
| Constituição Federal | Art. 5º, caput, inciso XXXIII | Garante o direito de acesso à informação a todos os cidadãos. |
| Constituição Federal | Art. 37, § 3º, inciso II | Estabelece que a lei deve garantir o acesso dos cidadãos às informações relativas à administração pública. |
| Constituição Federal | Art. 216, § 2º | Determina que o poder público deve garantir o acesso à informação sobre o patrimônio cultural brasileiro. |
| Lei nº 12.527/2011 | Não especificado | A Lei de Acesso à Informação estabelece as regras para o acesso à informação pública no Brasil. |
| Lei nº 7.115/1983 | Não especificado | Estabelece as regras para a declaração de situação econômica que permite a isenção de ressarcimento dos custos de acesso à informação. |

| Nome da norma | Artigo citado | Breve explicação do conteúdo do artigo |
| --- | --- | --- |
| Constituição Federal | Art. 5º, caput, inciso XXXIII | Garante o direito de acesso à informação a todos os cidadãos. |
| Constituição Federal | Art. 37, § 3º, inciso II | Estabelece que a lei deve garantir o acesso dos cidadãos às informações relativas à administração pública. |
| Constituição Federal | Art. 216, § 2º | Determina que o poder público deve garantir o acesso à informação sobre o patrimônio cultural brasileiro. |
| Lei nº 12.527/2011 | Não especificado | A Lei de Acesso à Informação estabelece as regras para o acesso à informação pública no Brasil. |
| Lei nº 7.115/1983 | Não especificado | Estabelece as regras para a declaração de situação econômica que permite a isenção de ressarcimento dos custos de acesso à informação. |


- Vamos agora pegar outra parte da LAI e aplicar o prompt anterior


In [46]:
parte_da_lai2 = f"""
VI - remuneração e subsídio recebidos por ocupante de cargo, posto, graduação, função e emprego público, incluídos os auxílios, as ajudas de custo, os jetons e outras vantagens pecuniárias, além dos proventos de aposentadoria e das pensões daqueles servidores e empregados públicos que estiverem na ativa, de maneira individualizada, conforme estabelecido em ato do Ministro de Estado da Economia; (Redação dada pelo Decreto nº 9.690, de 2019)

VII - respostas a perguntas mais frequentes da sociedade; (Redação dada pelo Decreto nº 8.408, de 2015)

VIII - contato da autoridade de monitoramento, designada nos termos do art. 40 da Lei nº 12.527, de 2011 , e telefone e correio eletrônico do Serviço de Informações ao Cidadão - SIC; e (Redação dada pelo Decreto nº 8.408, de 2015)

IX - programas financiados pelo Fundo de Amparo ao Trabalhador - FAT. (Incluído pelo Decreto nº 8.408, de 2015)

§ 4º As informações poderão ser disponibilizadas por meio de ferramenta de redirecionamento de página na Internet, quando estiverem disponíveis em outros sítios governamentais.

§ 5º No caso das empresas públicas, sociedades de economia mista e demais entidades controladas pela União que atuem em regime de concorrência, sujeitas ao disposto no art. 173 da Constituição, aplica-se o disposto no § 1º do art. 5º . 
"""

In [47]:
prompt = f"""
Quais normas jurídicas são citadas pelo documento jurídico delimitado por "###"? \

Organize os dados em uma tabela da seguinte forma: \
- coluna 1: nome da norma \
- coluna 2: artigo da norma que foi citada. \
- coluna 3: breve explicação do conteúdo da coluna 2, ou seja, do artigo da norma que foi citada. \

###{parte_da_lai2}###
"""
print_prompt_answer(prompt)

### Prompt


Quais normas jurídicas são citadas pelo documento jurídico delimitado por "###"? 
Organize os dados em uma tabela da seguinte forma: - coluna 1: nome da norma - coluna 2: artigo da norma que foi citada. - coluna 3: breve explicação do conteúdo da coluna 2, ou seja, do artigo da norma que foi citada. 
###
VI - remuneração e subsídio recebidos por ocupante de cargo, posto, graduação, função e emprego público, incluídos os auxílios, as ajudas de custo, os jetons e outras vantagens pecuniárias, além dos proventos de aposentadoria e das pensões daqueles servidores e empregados públicos que estiverem na ativa, de maneira individualizada, conforme estabelecido em ato do Ministro de Estado da Economia; (Redação dada pelo Decreto nº 9.690, de 2019)

VII - respostas a perguntas mais frequentes da sociedade; (Redação dada pelo Decreto nº 8.408, de 2015)

VIII - contato da autoridade de monitoramento, designada nos termos do art. 40 da Lei nº 12.527, de 2011 , e telefone e correio eletrônico do S

### Resposta

| Nome da norma | Artigo citado | Breve explicação |
| --- | --- | --- |
| Constituição Federal | Art. 173 | Estabelece que as empresas públicas, sociedades de economia mista e demais entidades controladas pela União que atuem em regime de concorrência devem seguir as normas do mercado, sujeitas ao disposto no § 1º do art. 5º. |
| Lei nº 12.527/2011 | Art. 40 | Estabelece que cada órgão ou entidade pública deve designar uma autoridade de monitoramento para garantir o cumprimento da lei de acesso à informação. |
| Decreto nº 8.408/2015 | VII | Estabelece que o documento deve conter respostas a perguntas mais frequentes da sociedade. |
| Decreto nº 8.408/2015 | VIII | Estabelece que o documento deve conter o contato da autoridade de monitoramento e do Serviço de Informações ao Cidadão - SIC. |
| Decreto nº 8.408/2015 | IX | Estabelece que o documento deve conter informações sobre programas financiados pelo Fundo de Amparo ao Trabalhador - FAT. |
| Decreto nº 9.690/2019 | VI | Estabelece que o documento deve conter informações sobre remuneração e subsídio recebidos por ocupante de cargo, posto, graduação, função e emprego público, incluídos os auxílios, as ajudas de custo, os jetons e outras vantagens pecuniárias, além dos proventos de aposentadoria e das pensões daqueles servidores e empregados públicos que estiverem na ativa, de maneira individualizada, conforme estabelecido em ato do Ministro de Estado da Economia. |
| Lei nº 12.527/2011 | § 4º | Estabelece que as informações podem ser disponibilizadas por meio de ferramenta de redirecionamento de página na Internet, quando estiverem disponíveis em outros sítios governamentais. |
| Constituição Federal | Art. 5º, § 1º | Estabelece que as empresas públicas, sociedades de economia mista e demais entidades controladas pela União que atuem em regime de concorrência devem seguir as normas do mercado, sujeitas ao disposto no § 1º do art. 5º. |

| Nome da norma | Artigo citado | Breve explicação |
| --- | --- | --- |
| Constituição Federal | Art. 173 | Estabelece que as empresas públicas, sociedades de economia mista e demais entidades controladas pela União que atuem em regime de concorrência devem seguir as normas do mercado, sujeitas ao disposto no § 1º do art. 5º. |
| Lei nº 12.527/2011 | Art. 40 | Estabelece que cada órgão ou entidade pública deve designar uma autoridade de monitoramento para garantir o cumprimento da lei de acesso à informação. |
| Decreto nº 8.408/2015 | VII | Estabelece que o documento deve conter respostas a perguntas mais frequentes da sociedade. |
| Decreto nº 8.408/2015 | VIII | Estabelece que o documento deve conter o contato da autoridade de monitoramento e do Serviço de Informações ao Cidadão - SIC. |
| Decreto nº 8.408/2015 | IX | Estabelece que o documento deve conter informações sobre programas financiados pelo Fundo de Amparo ao Trabalhador - FAT. |
| Decreto nº 9.690/2019 | VI | Estabelece 

- Vamos agora focar apenas nos Decretos
  - Trechos que foram citados
  - Contar quantas vezes os Decretos foram citados

In [48]:
prompt = f"""
Quais normas jurídicas do tipo "Decreto" são citadas pelo documento jurídico delimitado por "###"? \
Organize os dados em uma tabela da seguinte forma: \
- coluna 1: nome do Decreto. \
- coluna 2: trecho do Decreto que foi citado. \
- coluna 3: breve explicação do conteúdo da coluna 2, ou seja, do trecho do Decreto que foi citado. \
- coluna 4: quantidade de vezes que o Decreto foi citado no documento jurídico. \

###{parte_da_lai2}###
"""
print_prompt_answer(prompt)

### Prompt


Quais normas jurídicas do tipo "Decreto" são citadas pelo documento jurídico delimitado por "###"? Organize os dados em uma tabela da seguinte forma: - coluna 1: nome do Decreto. - coluna 2: trecho do Decreto que foi citado. - coluna 3: breve explicação do conteúdo da coluna 2, ou seja, do trecho do Decreto que foi citado. - coluna 4: quantidade de vezes que o Decreto foi citado no documento jurídico. 
###
VI - remuneração e subsídio recebidos por ocupante de cargo, posto, graduação, função e emprego público, incluídos os auxílios, as ajudas de custo, os jetons e outras vantagens pecuniárias, além dos proventos de aposentadoria e das pensões daqueles servidores e empregados públicos que estiverem na ativa, de maneira individualizada, conforme estabelecido em ato do Ministro de Estado da Economia; (Redação dada pelo Decreto nº 9.690, de 2019)

VII - respostas a perguntas mais frequentes da sociedade; (Redação dada pelo Decreto nº 8.408, de 2015)

VIII - contato da autoridade de monitor

### Resposta

| Nome do Decreto | Trecho citado | Breve explicação | Quantidade de vezes citado |
| --- | --- | --- | --- |
| Decreto nº 9.690, de 2019 | "VI - remuneração e subsídio recebidos por ocupante de cargo, posto, graduação, função e emprego público, incluídos os auxílios, as ajudas de custo, os jetons e outras vantagens pecuniárias, além dos proventos de aposentadoria e das pensões daqueles servidores e empregados públicos que estiverem na ativa, de maneira individualizada, conforme estabelecido em ato do Ministro de Estado da Economia;" | Estabelece a forma como deve ser divulgada a remuneração e subsídio dos servidores públicos, incluindo auxílios, ajudas de custo, jetons e outras vantagens pecuniárias. | 1 |
| Decreto nº 8.408, de 2015 | "VII - respostas a perguntas mais frequentes da sociedade;" | Estabelece a obrigatoriedade de disponibilização de respostas às perguntas mais frequentes da sociedade. | 1 |
| Decreto nº 8.408, de 2015 | "VIII - contato da autoridade de monitoramento, designada nos termos do art. 40 da Lei nº 12.527, de 2011 , e telefone e correio eletrônico do Serviço de Informações ao Cidadão - SIC; e" | Estabelece a obrigatoriedade de disponibilização de contato da autoridade de monitoramento e do Serviço de Informações ao Cidadão. | 1 |
| Decreto nº 8.408, de 2015 | "IX - programas financiados pelo Fundo de Amparo ao Trabalhador - FAT." | Estabelece a obrigatoriedade de disponibilização de informações sobre programas financiados pelo Fundo de Amparo ao Trabalhador. | 1 |

| Nome do Decreto | Trecho citado | Breve explicação | Quantidade de vezes citado |
| --- | --- | --- | --- |
| Decreto nº 9.690, de 2019 | "VI - remuneração e subsídio recebidos por ocupante de cargo, posto, graduação, função e emprego público, incluídos os auxílios, as ajudas de custo, os jetons e outras vantagens pecuniárias, além dos proventos de aposentadoria e das pensões daqueles servidores e empregados públicos que estiverem na ativa, de maneira individualizada, conforme estabelecido em ato do Ministro de Estado da Economia;" | Estabelece a forma como deve ser divulgada a remuneração e subsídio dos servidores públicos, incluindo auxílios, ajudas de custo, jetons e outras vantagens pecuniárias. | 1 |
| Decreto nº 8.408, de 2015 | "VII - respostas a perguntas mais frequentes da sociedade;" | Estabelece a obrigatoriedade de disponibilização de respostas às perguntas mais frequentes da sociedade. | 1 |
| Decreto nº 8.408, de 2015 | "VIII - contato da autoridade de monitoramento, de

- Vamos juntar as citações por Decreto: removendo a coluna do trecho

In [49]:
prompt = f"""
Quais normas jurídicas do tipo "Decreto" são citadas pelo documento jurídico delimitado por "###"? \
Organize os dados em uma tabela da seguinte forma: \
- coluna 1: nome do Decreto. \
- coluna 2: breve explicação do conteúdo da coluna 1, ou seja, do Decreto que foi citado. \
- coluna 3: quantidade de vezes que o Decreto foi citado no documento jurídico. \

###{parte_da_lai2}###
"""
print_prompt_answer(prompt)

### Prompt


Quais normas jurídicas do tipo "Decreto" são citadas pelo documento jurídico delimitado por "###"? Organize os dados em uma tabela da seguinte forma: - coluna 1: nome do Decreto. - coluna 2: breve explicação do conteúdo da coluna 1, ou seja, do Decreto que foi citado. - coluna 3: quantidade de vezes que o Decreto foi citado no documento jurídico. 
###
VI - remuneração e subsídio recebidos por ocupante de cargo, posto, graduação, função e emprego público, incluídos os auxílios, as ajudas de custo, os jetons e outras vantagens pecuniárias, além dos proventos de aposentadoria e das pensões daqueles servidores e empregados públicos que estiverem na ativa, de maneira individualizada, conforme estabelecido em ato do Ministro de Estado da Economia; (Redação dada pelo Decreto nº 9.690, de 2019)

VII - respostas a perguntas mais frequentes da sociedade; (Redação dada pelo Decreto nº 8.408, de 2015)

VIII - contato da autoridade de monitoramento, designada nos termos do art. 40 da Lei nº 12.527

### Resposta

| Nome do Decreto | Breve explicação | Quantidade de vezes citado |
| --- | --- | --- |
| Decreto nº 9.690, de 2019 | Estabelece a individualização da remuneração e subsídio recebidos por ocupantes de cargos públicos, incluindo auxílios, ajudas de custo, jetons e outras vantagens pecuniárias, além dos proventos de aposentadoria e pensões. | 1 |
| Decreto nº 8.408, de 2015 | Estabelece as respostas a perguntas frequentes da sociedade, o contato da autoridade de monitoramento e o telefone e correio eletrônico do Serviço de Informações ao Cidadão - SIC. Também inclui os programas financiados pelo Fundo de Amparo ao Trabalhador - FAT. | 3 |

| Nome do Decreto | Breve explicação | Quantidade de vezes citado |
| --- | --- | --- |
| Decreto nº 9.690, de 2019 | Estabelece a individualização da remuneração e subsídio recebidos por ocupantes de cargos públicos, incluindo auxílios, ajudas de custo, jetons e outras vantagens pecuniárias, além dos proventos de aposentadoria e pensões. | 1 |
| Decreto nº 8.408, de 2015 | Estabelece as respostas a perguntas frequentes da sociedade, o contato da autoridade de monitoramento e o telefone e correio eletrônico do Serviço de Informações ao Cidadão - SIC. Também inclui os programas financiados pelo Fundo de Amparo ao Trabalhador - FAT. | 3 |


### Sua vez :-)

1. Experimente os prompts anteriores com outro documento jurídico da sua escolha.
2. Evolua os prompts para que eles consigam extrair outro tipo de informação que você deseja.

## 2. Chatbot para Defensorias Públicas

- O objetivo é termos um chatbot que atenda assistidos de uma Defensoria Pública.
- Precisamos que o chatbot informe a lista de documentos necessários, etc. de acordo como seu fluxo de processo.
- O chatbot precisará dar encaminhamento à demanda do cidadão e encaminhá-lo ao defensor público



In [28]:
# criando funções específicas para interação via chatbot

def collect_messages(_):
    prompt = inp.value_input
    inp.value = ''
    context.append({'role':'user', 'content':f"{prompt}"})
    response = get_completion_from_messages(context) 
    context.append({'role':'assistant', 'content':f"{response}"})
    panels.append(
        pn.Row('User:', pn.pane.Markdown(prompt, width=600)))
    panels.append(
        pn.Row('Assistant:', pn.pane.Markdown(response, width=600, style={'background-color': '#F6F6F6'})))
 
    return pn.Column(*panels)

def get_completion_from_messages(messages, model="gpt-3.5-turbo", temperature=0):
    response = openai.ChatCompletion.create(
        model=model,
        messages=messages,
        temperature=temperature, # this is the degree of randomness of the model's output
    )
#     print(str(response.choices[0].message))
    return response.choices[0].message["content"]

import panel as pn  # GUI
pn.extension()

panels = [] # collect display 


In [3]:
# DPAL
documentos_necessarios = """ 

AÇÕES CÍVEIS :: ADJUDICAÇÃO COMPULSÓRIA

    Cópia da Carteira de Identidade e CPF do requerente
    Comprovante de renda (cópia do contracheque, benefício do INSS, declaração de isento do IR ou declaração de IR)
    Cópia de comprovante de residência (conta de água, luz ou telefone)
    Certidão de casamento do adquirente ou herdeiro
    Certidão de óbito
    Cópia do Contrato de Compra e venda – Escritura do imóvel ou Cessão de Direitos.
    Qualificação do herdeiro de quem vendeu
    Comprovante de quitação total (recibos)

AÇÕES CÍVEIS :: COBRANÇA DE DÍVIDA

    Cópia da Carteira de Identidade e CPF do requerente
    Comprovante de renda (cópia do contracheque, benefício do INSS, declaração de isento do IR ou declaração de IR)
    Cópia de comprovante de residência (conta de água, luz ou telefone)
    Cópia dos documentos que comprovam a existência da dívida
    Nome e endereço do devedor

AÇÕES CÍVEIS :: CONSIGNAÇÃO EM PAGAMENTO

    Cópia da Carteira de Identidade e CPF do requerente
    Comprovante de renda (cópia do contracheque, benefício do INSS, declaração de isento do IR ou declaração de IR)
    Cópia de comprovante de residência (conta de água, luz ou telefone)
    Cópia dos documentos que demonstrem a dívida
    Informar o motivo da recusa do credor em receber ou dificuldade de fazer o pagamento e qual quantia deseja depositar
    Nome e endereço do credor

AÇÕES CÍVEIS :: DEMOLITÓRIA

    Cópia da Carteira de Identidade e CPF do requerente
    Comprovante de renda (cópia do contracheque, benefício do INSS, declaração de isento do IR ou declaração de IR)
    Cópia de comprovante de residência (conta de água, luz ou telefone)
    Cópia do contrato de compra e venda do imóvel ou escritura pública
    Laudo técnico (se houver)
    Nome e endereço do requerido
    Nome e endereço de 03 (três) testemunhas
    Fotografias do que pretende demolir

AÇÕES CÍVEIS :: DESPEJO PARA FALTA DE PAGAMENTO

    Cópia da Carteira de Identidade e CPF do requerente
    Comprovante de renda (cópia do contracheque, benefício do INSS, declaração de isento do IR ou declaração de IR)
    Cópia de comprovante de residência (conta de água, luz ou telefone)
    Cópia do contrato de locação
    Nome e endereço do inquilino (locatário)
"""

In [4]:
# contexto do chatbot, aqui você personaliza o chatbot com todas as regras do fluxo de processo
context = [ {'role':'system', 'content':f"""
Você é um chatbot de atendimento de pessoas assistidas pela Defensoria Pública. \
Seu objetivo é instruir o assistido com a lista de documentos necessários para que \
o assistido possa ser encaminhado para atendimento com um defensor público. \
Seja cordial e empático. \
Primeiramente, cumprimente o assistido, pergunte seu nome e pergunte qual é a sua demanda. \
Em alguns casos específicos, forneça a lista de documentos que o assistido deve providenciar. \
Esse casos específicos são descritos no documento entre aspas triplas "```", onde cada tipo de \
ação judicial vai exigir uma lista de documentos. \
Em relação aos casos específicos, não conclua o atendimento até que o assistido receba a lista \
de documentos necessários para entrar com uma ação judicial. \
Para os demais casos não específicos, não forneça a lista de documentos necessários. \
Após cumprir os requisitos citados anteriormente, encaminhe o assistido para atendimento presencial \
com defensor público no endereço "Av. 2 de julho, n. 20". \
Para o encaminhamento do assisitdo para um defensor público, é necessário coletar todas essas \
informações sobre o assistido: nome e contato. \
Outro critério necessário para que você possa encaminhar o assisitido a um defensor público é que  \
a renda mensal do assistido seja inferior a 3 salários mínimos, ou seja, R$ 3.960. \
```
{documentos_necessarios}
```
"""} ]


inp = pn.widgets.TextInput(value="Olá, sou o assistente virtual da Defensoria Pública! Como poderia te ajudar?", 
                           placeholder='Escreva aqui a sua demanda ou solicitação...')
button_conversation = pn.widgets.Button(name="Enviar")

interactive_conversation = pn.bind(collect_messages, button_conversation)

dashboard = pn.Column(
    inp,
    pn.Row(button_conversation),
    pn.panel(interactive_conversation, loading_indicator=True, height=900),
)

dashboard

Column
    [0] TextInput(placeholder='Escreva aqui a...)
    [1] Row
        [0] Button(name='Enviar')
    [2] ParamFunction(function, _pane=Column, height=900, loading_indicator=True)

### Sua vez :-)

1. Modifique o exemplo do chatbot para o atendimento de clientes de um escritório especializado em Direito Tributário e adeque as regras de acordo com o fluxo de processo desse escritório
2. Modifique o exemplo do chatbot para o agendamento de atendimento de uma parte com o um magistrado, crie as regras que for necessárias para os critérios de atendimento da Vara

## 3. Elaboração de documentos jurídicos

### 3.1 Elaboração de Petição Inicial

- Mulher divorciada com renda de um salário mínimo
- Fiho menor com deficiência física

Vamos começar com a abordagem ingênua:


In [50]:
prompt = f"""
Prepare uma petição inicial para o pagamento de pensão alimentícia para menor com deficiência física.

"""

print_prompt_answer(prompt)

### Prompt


Prepare uma petição inicial para o pagamento de pensão alimentícia para menor com deficiência física.




### Resposta

EXCELENTÍSSIMO SENHOR JUIZ DE DIREITO DA VARA DE FAMÍLIA DA COMARCA DE [CIDADE/ESTADO]

[NOME DO REQUERENTE], brasileiro, [estado civil], [profissão], portador do RG nº [número do RG] e CPF nº [número do CPF], residente e domiciliado na [endereço completo], vem, por meio de seu advogado [nome do advogado], inscrito na OAB/[estado] sob o nº [número da inscrição], com escritório profissional na [endereço completo], onde recebe intimações, propor a presente

AÇÃO DE ALIMENTOS

em face de [NOME DO REQUERIDO], brasileiro, [estado civil], [profissão], portador do RG nº [número do RG] e CPF nº [número do CPF], residente e domiciliado na [endereço completo], pelos motivos de fato e de direito a seguir expostos:

I – DOS FATOS

O requerente é pai do menor [NOME DO MENOR], nascido em [DATA DE NASCIMENTO], portador de deficiência física, conforme atestado médico anexo.

O requerido é o genitor do menor e, apesar de ter a obrigação legal de prestar alimentos ao filho, não vem cumprindo com tal obrigação, deixando o requerente em situação de extrema dificuldade financeira para arcar com as despesas do menor.

O requerente, por sua vez, não possui condições financeiras para arcar sozinho com todas as despesas do menor, que necessita de cuidados especiais em razão de sua deficiência física.

II – DO DIREITO

O direito à pensão alimentícia é garantido pela Constituição Federal, em seu artigo 227, que estabelece a obrigação dos pais de prestar assistência material aos filhos.

Além disso, o Código Civil, em seu artigo 1.694, estabelece que os pais têm o dever de prestar alimentos aos filhos, de acordo com suas possibilidades e necessidades.

No caso em questão, o menor é portador de deficiência física, o que implica em maiores gastos com tratamentos médicos, medicamentos, fisioterapia, entre outros, o que torna ainda mais necessária a prestação de alimentos pelo requerido.

III – DO PEDIDO

Diante do exposto, requer o requerente:

a) A concessão de alimentos em favor do menor [NOME DO MENOR], no valor correspondente a [VALOR DA PENSÃO], a ser pago mensalmente pelo requerido;

b) A intimação do requerido para, querendo, apresentar resposta no prazo legal;

c) A produção de todas as provas admitidas em direito, especialmente a documental e a testemunhal;

d) A condenação do requerido ao pagamento das custas processuais e honorários advocatícios.

IV – DO VALOR DA CAUSA

Dá-se à causa o valor de [VALOR DA PENSÃO], para fins fiscais e de alçada.

Nestes termos, pede deferimento.

[LOCAL], [DATA]

[NOME DO ADVOGADO]

OAB/[ESTADO] nº [NÚMERO DA INSCRIÇÃO]

EXCELENTÍSSIMO SENHOR JUIZ DE DIREITO DA VARA DE FAMÍLIA DA COMARCA DE [CIDADE/ESTADO]

[NOME DO REQUERENTE], brasileiro, [estado civil], [profissão], portador do RG nº [número do RG] e CPF nº [número do CPF], residente e domiciliado na [endereço completo], vem, por meio de seu advogado [nome do advogado], inscrito na OAB/[estado] sob o nº [número da inscrição], com escritório profissional na [endereço completo], onde recebe intimações, propor a presente

AÇÃO DE ALIMENTOS

em face de [NOME DO REQUERIDO], brasileiro, [estado civil], [profissão], portador do RG nº [número do RG] e CPF nº [número do CPF], residente e domiciliado na [endereço completo], pelos motivos de fato e de direito a seguir expostos:

I – DOS FATOS

O requerente é pai do menor [NOME DO MENOR], nascido em [DATA DE NASCIMENTO], portador de deficiência física, conforme atestado médico anexo.

O requerido é o genitor do menor e, apesar de ter a obrigação legal de prestar alimentos ao filho, não vem cumprindo com tal obr

### Analizando o prompt

- Agora, vamos especificar melhor de acordo com as peculiaridades deste caso fictício...

In [51]:
prompt = f"""
Prepare uma petição inicial para o pagamento de pensão alimentícia. \

Leve em consideração as seguintes informações: \

- A petição será encaminhada para a Vara da Família do TJSP. \ 
- A solicitante é uma mulher divorciada cuja renda é de um salário mínimo. \
- A solicitante tem um filho menor com deficiência física. \
- Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia. \
- Atue como um advogado especializado em Direito da Família. \

"""

print_prompt_answer(prompt)

### Prompt


Prepare uma petição inicial para o pagamento de pensão alimentícia. 
Leve em consideração as seguintes informações: 
- A petição será encaminhada para a Vara da Família do TJSP. \ 
- A solicitante é uma mulher divorciada cuja renda é de um salário mínimo. - A solicitante tem um filho menor com deficiência física. - Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia. - Atue como um advogado especializado em Direito da Família. 



### Resposta

EXCELENTÍSSIMO SENHOR JUIZ DE DIREITO DA VARA DA FAMÍLIA DO TRIBUNAL DE JUSTIÇA DO ESTADO DE SÃO PAULO

NOME DA SOLICITANTE, brasileira, divorciada, portadora do RG nº XXXXXXXX e do CPF nº XXXXXXXX, residente e domiciliada na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, Cidade XXXXXXXX, Estado XXXXXXXX, por meio de seu advogado infra-assinado, vem, respeitosamente, à presença de Vossa Excelência, propor a presente

AÇÃO DE ALIMENTOS

em face de NOME DO PAI, brasileiro, portador do RG nº XXXXXXXX e do CPF nº XXXXXXXX, residente e domiciliado na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, Cidade XXXXXXXX, Estado XXXXXXXX, pelos motivos de fato e de direito a seguir expostos:

I – DOS FATOS

A requerente é mãe de um filho menor, portador de deficiência física, fruto do relacionamento com o requerido. O casal se divorciou em XX/XX/XXXX, e ficou acordado que o requerido pagaria pensão alimentícia ao filho no valor de R$ XXX,XX (XXXXX reais) mensais.

No entanto, o requerido nunca cumpriu com sua obrigação alimentar, deixando a requerente e seu filho em situação de extrema vulnerabilidade financeira. A requerente, por sua vez, possui renda mensal de apenas um salário mínimo, o que não é suficiente para arcar com as despesas do filho.

O requerido, por sua vez, possui renda mensal de R$ 5.000,00 (cinco mil reais), conforme comprovante de rendimentos anexado.

II – DO DIREITO

A obrigação alimentar é um dever recíproco entre pais e filhos, previsto no artigo 229 da Constituição Federal e nos artigos 1.694 a 1.710 do Código Civil. O objetivo é garantir a subsistência do alimentando, assegurando-lhe condições dignas de vida.

No caso em tela, o requerido tem o dever de prestar alimentos ao filho menor, conforme acordado no divórcio. O não pagamento da pensão alimentícia configura ato ilícito, passível de sanções civis e criminais.

III – DO PEDIDO

Diante do exposto, requer a Vossa Excelência:

a) A citação do requerido para, querendo, apresentar resposta no prazo legal;

b) A condenação do requerido ao pagamento de pensão alimentícia ao filho menor, no valor de R$ XXX,XX (XXXXX reais) mensais, a ser depositado na conta bancária da requerente, a partir da citação;

c) A fixação de alimentos provisórios no valor de R$ XXX,XX (XXXXX reais) mensais, a serem pagos pelo requerido até o julgamento final da presente ação;

d) A condenação do requerido ao pagamento das custas processuais e honorários advocatícios.

IV – DO VALOR DA CAUSA

Dá-se à causa o valor de R$ XXX,XX (XXXXX reais), para fins fiscais e de alçada.

Nestes termos, pede deferimento.

Local, data.

Advogado XXXXXXXX

OAB/XX nº XXXXXXXX

EXCELENTÍSSIMO SENHOR JUIZ DE DIREITO DA VARA DA FAMÍLIA DO TRIBUNAL DE JUSTIÇA DO ESTADO DE SÃO PAULO

NOME DA SOLICITANTE, brasileira, divorciada, portadora do RG nº XXXXXXXX e do CPF nº XXXXXXXX, residente e domiciliada na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, Cidade XXXXXXXX, Estado XXXXXXXX, por meio de seu advogado infra-assinado, vem, respeitosamente, à presença de Vossa Excelência, propor a presente

AÇÃO DE ALIMENTOS

em face de NOME DO PAI, brasileiro, portador do RG nº XXXXXXXX e do CPF nº XXXXXXXX, residente e domiciliado na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, Cidade XXXXXXXX, Estado XXXXXXXX, pelos motivos de fato e de direito a seguir expostos:

I – DOS FATOS

A requerente é mãe de um filho menor, portador de deficiência física, fruto do relacionamento com o requerido. O casal se divorciou em XX/XX/XXXX, e ficou acordado que o requerido pagaria pensão alimentícia ao filho no valor de R$ XXX,XX (XXXXX reais) mensais.

No entanto, o requerido nunca cumpriu com sua obrigaç

### Analizando o prompt

- Vamos tentar moldar o discurso para que ele fique mais apelativo:

In [52]:
prompt = f"""
Prepare uma petição inicial para o pagamento de pensão alimentícia. \

Leve em consideração as seguintes informações: \

- A petição será encaminhada para a Vara da Família do TJSP. \ 
- A solicitante é uma mulher divorciada cuja renda é de um salário mínimo. \
- A solicitante tem um filho menor com deficiência física. \
- Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia. \
- Atue como um advogado especializado em Direito da Família. \

- Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e \
a condição de pessoa com deficiência do seu filho. \
"""

print_prompt_answer(prompt)

### Prompt


Prepare uma petição inicial para o pagamento de pensão alimentícia. 
Leve em consideração as seguintes informações: 
- A petição será encaminhada para a Vara da Família do TJSP. \ 
- A solicitante é uma mulher divorciada cuja renda é de um salário mínimo. - A solicitante tem um filho menor com deficiência física. - Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia. - Atue como um advogado especializado em Direito da Família. 
- Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e a condição de pessoa com deficiência do seu filho. 


### Resposta

EXCELENTÍSSIMO SENHOR JUIZ DE DIREITO DA VARA DA FAMÍLIA DO TRIBUNAL DE JUSTIÇA DO ESTADO DE SÃO PAULO

NOME DA SOLICITANTE, brasileira, divorciada, portadora do RG nº XXXXXXXX e do CPF nº XXXXXXXX, residente e domiciliada na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, Cidade XXXXXXXX, Estado XXXXXXXX, por meio de seu advogado infra-assinado, vem, respeitosamente, à presença de Vossa Excelência, propor a presente AÇÃO DE ALIMENTOS em face de NOME DO PAI, brasileiro, portador do RG nº XXXXXXXX e do CPF nº XXXXXXXX, residente e domiciliado na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, Cidade XXXXXXXX, Estado XXXXXXXX, pelos motivos de fato e de direito a seguir expostos:

I – DOS FATOS

A requerente é mãe de um filho menor, portador de deficiência física, que necessita de cuidados especiais e tratamentos médicos constantes. A requerente é divorciada do requerido e, desde a separação, o requerido nunca pagou a pensão alimentícia devida ao filho.

A requerente é uma pessoa de baixa renda, que sobrevive com um salário mínimo mensal, o que torna impossível arcar com as despesas necessárias para a manutenção do filho.

O requerido, por sua vez, possui uma renda mensal de R$ 5.000,00, o que lhe permite arcar com as despesas alimentares do filho.

II – DO DIREITO

O direito à pensão alimentícia é garantido pela Constituição Federal e pelo Código Civil, que estabelecem a obrigação dos pais de proverem o sustento dos filhos.

O requerido, na qualidade de pai, tem o dever de prestar alimentos ao filho menor, especialmente por se tratar de uma criança com deficiência física, que necessita de cuidados especiais e tratamentos médicos constantes.

III – DO PEDIDO

Diante do exposto, requer a Vossa Excelência:

a) A concessão de tutela de urgência para que o requerido seja obrigado a pagar, desde já, a pensão alimentícia no valor de R$ XXX,XX (valor a ser definido pelo juiz), a ser depositada na conta bancária da requerente, sob pena de multa diária de R$ XXX,XX (valor a ser definido pelo juiz);

b) A fixação da pensão alimentícia definitiva no valor de R$ XXX,XX (valor a ser definido pelo juiz), a ser paga mensalmente pelo requerido, a partir da citação, até que o filho complete a maioridade ou deixe de necessitar dos cuidados especiais;

c) A condenação do requerido ao pagamento das custas processuais e honorários advocatícios.

IV – DOS REQUERIMENTOS FINAIS

Requer a requerente a produção de todas as provas admitidas em direito, especialmente a juntada de documentos, depoimento pessoal do requerido, oitiva de testemunhas e realização de perícia médica.

Dá-se à causa o valor de R$ XXX,XX (valor a ser definido pelo juiz) para fins fiscais.

Nestes termos, pede deferimento.

Local, data.

Advogado XXXXXXXX

OAB/XX nº XXXXXXXX

EXCELENTÍSSIMO SENHOR JUIZ DE DIREITO DA VARA DA FAMÍLIA DO TRIBUNAL DE JUSTIÇA DO ESTADO DE SÃO PAULO

NOME DA SOLICITANTE, brasileira, divorciada, portadora do RG nº XXXXXXXX e do CPF nº XXXXXXXX, residente e domiciliada na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, Cidade XXXXXXXX, Estado XXXXXXXX, por meio de seu advogado infra-assinado, vem, respeitosamente, à presença de Vossa Excelência, propor a presente AÇÃO DE ALIMENTOS em face de NOME DO PAI, brasileiro, portador do RG nº XXXXXXXX e do CPF nº XXXXXXXX, residente e domiciliado na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, Cidade XXXXXXXX, Estado XXXXXXXX, pelos motivos de fato e de direito a seguir expostos:

I – DOS FATOS

A requerente é mãe de um filho menor, portador de deficiência física, que necessita de cuidados especiais e tratamentos médicos constantes. A requerente é divorciada do requerido e, desde a separação, o requerido nunca pagou a pensão alimentícia devida ao filho.

A requerente é uma pessoa de baixa renda, que sobrevi

### Analizando o prompt

- Vamos tentar melhorar a narrativa para um discurso mais amplo da sensibilização da situação

In [53]:
prompt = f"""
Prepare uma petição inicial para o pagamento de pensão alimentícia. \

Leve em consideração as seguintes informações: \

- A petição será encaminhada para a Vara da Família do TJSP. \ 
- A solicitante é uma mulher divorciada cuja renda é de um salário mínimo. \
- A solicitante tem um filho menor com deficiência física. \
- Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia. \
- Atue como um advogado especializado em Direito da Família. \

- Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e \
a condição de pessoa com deficiência do seu filho. \
- Ao narrar os fatos, seja bem detalhista, criativo e narre de forma ampla a situação. \
"""

print_prompt_answer(prompt)

### Prompt


Prepare uma petição inicial para o pagamento de pensão alimentícia. 
Leve em consideração as seguintes informações: 
- A petição será encaminhada para a Vara da Família do TJSP. \ 
- A solicitante é uma mulher divorciada cuja renda é de um salário mínimo. - A solicitante tem um filho menor com deficiência física. - Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia. - Atue como um advogado especializado em Direito da Família. 
- Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e a condição de pessoa com deficiência do seu filho. - Ao narrar os fatos, seja bem detalhista, criativo e narre de forma ampla a situação. 


### Resposta

EXCELENTÍSSIMO SENHOR JUIZ DE DIREITO DA VARA DA FAMÍLIA DO TRIBUNAL DE JUSTIÇA DO ESTADO DE SÃO PAULO

NOME DA SOLICITANTE, brasileira, divorciada, portadora do RG nº XXXXXXXX e do CPF nº XXXXXXXX, residente e domiciliada na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, Cidade XXXXXXXX, Estado de São Paulo, por intermédio de seu advogado, vem, respeitosamente, à presença de Vossa Excelência, propor a presente AÇÃO DE ALIMENTOS em face de NOME DO PAI, brasileiro, portador do RG nº XXXXXXXX e do CPF nº XXXXXXXX, residente e domiciliado na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, Cidade XXXXXXXX, Estado de São Paulo, pelos motivos de fato e de direito a seguir expostos:

I - DOS FATOS

A requerente é mãe de um filho menor, portador de deficiência física, que necessita de cuidados especiais e tratamentos médicos constantes. A requerente é divorciada do requerido e, desde a separação, o requerido nunca pagou a pensão alimentícia devida ao filho.

A requerente é uma pessoa de baixa renda, que sobrevive com um salário mínimo mensal, o que torna impossível arcar com as despesas necessárias para a manutenção do filho. O requerido, por sua vez, possui uma renda mensal de R$ 5.000,00, o que lhe permite arcar com o pagamento da pensão alimentícia.

II - DO DIREITO

O direito à pensão alimentícia é garantido pela Constituição Federal e pelo Código Civil, que estabelecem a obrigação dos pais de proverem o sustento dos filhos menores. Além disso, a Lei nº 13.146/2015, que institui a Lei Brasileira de Inclusão da Pessoa com Deficiência, prevê a necessidade de garantir a proteção social e o acesso aos serviços públicos e privados para as pessoas com deficiência.

III - DO PEDIDO

Diante do exposto, requer a Vossa Excelência:

a) A concessão de liminar para que o requerido pague imediatamente a pensão alimentícia devida ao filho, no valor de 30% de sua renda mensal, conforme estabelecido pela jurisprudência;

b) A condenação do requerido ao pagamento da pensão alimentícia mensal, no valor de 30% de sua renda mensal, a ser depositada na conta bancária indicada pela requerente;

c) A fixação de multa diária em caso de descumprimento da obrigação alimentar;

d) A condenação do requerido ao pagamento das custas processuais e honorários advocatícios.

IV - DO VALOR DA CAUSA

Dá-se à causa o valor de R$ XXXXXXXX (valor da pensão alimentícia devida desde a separação).

Nestes termos, pede deferimento.

Local, data.

Advogado

OAB/XX nº XXXXXXXX

EXCELENTÍSSIMO SENHOR JUIZ DE DIREITO DA VARA DA FAMÍLIA DO TRIBUNAL DE JUSTIÇA DO ESTADO DE SÃO PAULO

NOME DA SOLICITANTE, brasileira, divorciada, portadora do RG nº XXXXXXXX e do CPF nº XXXXXXXX, residente e domiciliada na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, Cidade XXXXXXXX, Estado de São Paulo, por intermédio de seu advogado, vem, respeitosamente, à presença de Vossa Excelência, propor a presente AÇÃO DE ALIMENTOS em face de NOME DO PAI, brasileiro, portador do RG nº XXXXXXXX e do CPF nº XXXXXXXX, residente e domiciliado na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, Cidade XXXXXXXX, Estado de São Paulo, pelos motivos de fato e de direito a seguir expostos:

I - DOS FATOS

A requerente é mãe de um filho menor, portador de deficiência física, que necessita de cuidados especiais e tratamentos médicos constantes. A requerente é divorciada do requerido e, desde a separação, o requerido nunca pagou a pensão alimentícia devida ao filho.

A requerente é uma pessoa de baixa renda, que sobreviv

### Analizando o prompt

- Vamos tentar informar a quantidade de palavras na narrativa dos fatos

In [54]:
prompt = f"""
Quantas palavras tem nesse parágrafo?

A requerente é mãe de um filho menor, portador de deficiência física, que necessita de cuidados especiais e tratamentos médicos constantes. A requerente é divorciada do pai da criança, que nunca pagou a pensão alimentícia, mesmo tendo condições financeiras para tal.

O pai da criança, Sr. XXXXXXXX, possui renda mensal de R$ 5.000,00 (cinco mil reais), mas nunca contribuiu com a pensão alimentícia do filho, deixando a requerente em situação financeira precária, tendo em vista que sua renda é de apenas um salário mínimo.

A situação da requerente e de seu filho é extremamente delicada, pois a criança necessita de cuidados especiais e tratamentos médicos constantes, o que acarreta em gastos elevados e que a requerente não tem condições de arcar sozinha.
"""

print_prompt_answer(prompt)

### Prompt


Quantas palavras tem nesse parágrafo?

A requerente é mãe de um filho menor, portador de deficiência física, que necessita de cuidados especiais e tratamentos médicos constantes. A requerente é divorciada do pai da criança, que nunca pagou a pensão alimentícia, mesmo tendo condições financeiras para tal.

O pai da criança, Sr. XXXXXXXX, possui renda mensal de R$ 5.000,00 (cinco mil reais), mas nunca contribuiu com a pensão alimentícia do filho, deixando a requerente em situação financeira precária, tendo em vista que sua renda é de apenas um salário mínimo.

A situação da requerente e de seu filho é extremamente delicada, pois a criança necessita de cuidados especiais e tratamentos médicos constantes, o que acarreta em gastos elevados e que a requerente não tem condições de arcar sozinha.



### Resposta

87 palavras.

87 palavras.


### Analizando o prompt

- Vamos então pedir para usar 200 palavras para narrar os fatos

In [55]:
prompt = f"""
Prepare uma petição inicial para o pagamento de pensão alimentícia. \

Leve em consideração as seguintes informações: \

- A petição será encaminhada para a Vara da Família do TJSP. \ 
- A solicitante é uma mulher divorciada cuja renda é de um salário mínimo. \
- A solicitante tem um filho menor com deficiência física. \
- Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia. \
- Atue como um advogado especializado em Direito da Família. \

- Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e \
a condição de pessoa com deficiência do seu filho. \
- Ao narrar os fatos, seja bem detalhista, criativo e narre de forma ampla a situação. \
- Ao narrar os fatos, use 200 palavras. \
"""

print_prompt_answer(prompt)

### Prompt


Prepare uma petição inicial para o pagamento de pensão alimentícia. 
Leve em consideração as seguintes informações: 
- A petição será encaminhada para a Vara da Família do TJSP. \ 
- A solicitante é uma mulher divorciada cuja renda é de um salário mínimo. - A solicitante tem um filho menor com deficiência física. - Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia. - Atue como um advogado especializado em Direito da Família. 
- Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e a condição de pessoa com deficiência do seu filho. - Ao narrar os fatos, seja bem detalhista, criativo e narre de forma ampla a situação. - Ao narrar os fatos, use 200 palavras. 


### Resposta

EXCELENTÍSSIMO SENHOR JUIZ DE DIREITO DA VARA DA FAMÍLIA DO TJSP

FULANA DE TAL, brasileira, divorciada, portadora do RG nº XXXXXXXX e CPF nº XXXXXXXX, residente e domiciliada na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, na cidade de São Paulo, vem, por meio de seu advogado, com fundamento no artigo 1.694 do Código Civil e artigo 528 do Código de Processo Civil, requerer a fixação de pensão alimentícia em face de BELTRANO DE TAL, brasileiro, solteiro, portador do RG nº XXXXXXXX e CPF nº XXXXXXXX, residente e domiciliado na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, na cidade de São Paulo, pelos motivos a seguir expostos:

A requerente é mãe de um filho menor, com deficiência física, que necessita de cuidados especiais e tratamentos médicos constantes. A requerente é divorciada e possui renda mensal de apenas um salário mínimo, o que não é suficiente para arcar com todas as despesas do filho.

O requerido, por sua vez, possui renda mensal de R$ 5.000,00 e nunca pagou a pensão alimentícia devida ao filho. A situação financeira da requerente é precária e a falta de pagamento da pensão alimentícia pelo requerido tem gerado grande dificuldade para a manutenção das necessidades básicas do filho.

Diante do exposto, requer-se a fixação de pensão alimentícia no valor de 30% do salário do requerido, ou seja, R$ 1.500,00 mensais, a serem depositados na conta bancária da requerente, a fim de garantir a subsistência do filho menor.

Por fim, a requerente apela à sensibilidade deste juízo para que seja concedida a pensão alimentícia pleiteada, tendo em vista a condição de pessoa com deficiência do filho e a precária situação financeira da requerente.

Nestes termos, pede deferimento.

Local e data.

Advogado: XXXXXXXX

OAB/XX nº XXXXXXXX

EXCELENTÍSSIMO SENHOR JUIZ DE DIREITO DA VARA DA FAMÍLIA DO TJSP

FULANA DE TAL, brasileira, divorciada, portadora do RG nº XXXXXXXX e CPF nº XXXXXXXX, residente e domiciliada na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, na cidade de São Paulo, vem, por meio de seu advogado, com fundamento no artigo 1.694 do Código Civil e artigo 528 do Código de Processo Civil, requerer a fixação de pensão alimentícia em face de BELTRANO DE TAL, brasileiro, solteiro, portador do RG nº XXXXXXXX e CPF nº XXXXXXXX, residente e domiciliado na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, na cidade de São Paulo, pelos motivos a seguir expostos:

A requerente é mãe de um filho menor, com deficiência física, que necessita de cuidados especiais e tratamentos médicos constantes. A requerente é divorciada e possui renda mensal de apenas um salário mínimo, o que não é suficiente para arcar com todas as despesas do filho.

O requerido, por sua vez, possui renda mensal de R$ 5.000,00 e nunca pagou a pensão alimentícia devida 

### Analizando o prompt

- Ele piorou, pois entendeu que "narrar os fatos" fosse a Petição Inicial e não a seção DOS FATOS
- Vamos tentar corrigir

In [56]:
prompt = f"""
Prepare uma petição inicial para o pagamento de pensão alimentícia. \

Leve em consideração as seguintes informações: \

- A petição será encaminhada para a Vara da Família do TJSP. \ 
- A solicitante é uma mulher divorciada cuja renda é de um salário mínimo. \
- A solicitante tem um filho menor com deficiência física. \
- Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia. \
- Atue como um advogado especializado em Direito da Família. \

- Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e \
a condição de pessoa com deficiência do seu filho. \
- Na seção intitulada "DOS FATOS" da Petição Inicial, seja bem detalhista, criativo \
e narre de forma ampla a situação. \
- Na seção intitulada "DOS FATOS" da Petição Inicial, use 200 palavras. \
- Para elaborar a Petição Inicial, use 2000 tokens. \
"""

print_prompt_answer(prompt)

### Prompt


Prepare uma petição inicial para o pagamento de pensão alimentícia. 
Leve em consideração as seguintes informações: 
- A petição será encaminhada para a Vara da Família do TJSP. \ 
- A solicitante é uma mulher divorciada cuja renda é de um salário mínimo. - A solicitante tem um filho menor com deficiência física. - Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia. - Atue como um advogado especializado em Direito da Família. 
- Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e a condição de pessoa com deficiência do seu filho. - Na seção intitulada "DOS FATOS" da Petição Inicial, seja bem detalhista, criativo e narre de forma ampla a situação. - Na seção intitulada "DOS FATOS" da Petição Inicial, use 200 palavras. - Para elaborar a Petição Inicial, use 2000 tokens. 


### Resposta

EXCELENTÍSSIMO SENHOR JUIZ DE DIREITO DA VARA DA FAMÍLIA DO TRIBUNAL DE JUSTIÇA DO ESTADO DE SÃO PAULO

NOME DA SOLICITANTE, brasileira, divorciada, portadora do RG nº XXXXXXXX e do CPF nº XXXXXXXX, residente e domiciliada na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, Cidade XXXXXXXX, Estado de São Paulo, por meio de seu advogado, vem, respeitosamente, à presença de Vossa Excelência, propor a presente AÇÃO DE ALIMENTOS em face de NOME DO PAI, brasileiro, portador do RG nº XXXXXXXX e do CPF nº XXXXXXXX, residente e domiciliado na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, Cidade XXXXXXXX, Estado de São Paulo, pelos fatos e fundamentos a seguir expostos:

DOS FATOS

A requerente é mãe de um filho menor, portador de deficiência física, que necessita de cuidados especiais e tratamentos médicos constantes. A requerente é divorciada do requerido e, desde a separação, o requerido nunca pagou a pensão alimentícia devida ao filho.

A requerente é uma pessoa de baixa renda, que sobrevive com um salário mínimo mensal, o que torna impossível arcar com as despesas necessárias para a manutenção do filho. O requerido, por sua vez, possui uma renda mensal de R$ 5.000,00, o que lhe permite arcar com o pagamento da pensão alimentícia.

A situação da requerente e do filho é extremamente delicada, uma vez que a falta de recursos financeiros impede a realização de tratamentos médicos e aquisição de medicamentos necessários para a saúde do menor. A situação é ainda mais grave em razão da deficiência física do filho, que exige cuidados especiais e tratamentos específicos.

Dessa forma, a requerente vem, por meio desta ação, requerer o pagamento de pensão alimentícia em favor do filho menor, no valor correspondente a 30% dos rendimentos líquidos do requerido, a serem depositados mensalmente em conta bancária a ser indicada pela requerente.

DO DIREITO

O direito à pensão alimentícia é garantido pela Constituição Federal e pelo Código Civil, que estabelecem a obrigação dos pais de proverem o sustento dos filhos menores. Além disso, a deficiência física do filho da requerente torna ainda mais evidente a necessidade de assistência financeira por parte do requerido.

DO PEDIDO

Diante do exposto, requer a Vossa Excelência:

a) A citação do requerido para, querendo, apresentar resposta à presente ação;

b) A condenação do requerido ao pagamento de pensão alimentícia em favor do filho menor, no valor correspondente a 30% dos rendimentos líquidos do requerido, a serem depositados mensalmente em conta bancária a ser indicada pela requerente;

c) A condenação do requerido ao pagamento das custas processuais e honorários advocatícios.

Protesta provar o alegado por todos os meios de prova em direito admitidos, especialmente pela juntada de documentos, depoimento pessoal do requerido, oitiva de testemunhas e demais provas que se fizerem necessárias.

Dá-se à causa o valor de R$ XXXXXXXX.

Termos em que,

Pede deferimento.

Local, data.

Assinatura do advogado.

EXCELENTÍSSIMO SENHOR JUIZ DE DIREITO DA VARA DA FAMÍLIA DO TRIBUNAL DE JUSTIÇA DO ESTADO DE SÃO PAULO

NOME DA SOLICITANTE, brasileira, divorciada, portadora do RG nº XXXXXXXX e do CPF nº XXXXXXXX, residente e domiciliada na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, Cidade XXXXXXXX, Estado de São Paulo, por meio de seu advogado, vem, respeitosamente, à presença de Vossa Excelência, propor a presente AÇÃO DE ALIMENTOS em face de NOME DO PAI, brasileiro, portador do RG nº XXXXXXXX e do CPF nº XXXXXXXX, residente e domiciliado na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, Cidade XXXXXXXX, Estado de São Paulo, pelos fatos e fundamentos a seguir expostos:

DOS FATOS

A requerente é mãe de um filho menor, portador de deficiência física, que necessita de cuidados especiais e tratamentos médicos constantes. A requerente é divorciada do requerido e, desde a separação, o requerido nunca pagou a pensão alimentícia devida ao filho.

A requerente é uma pessoa de baixa renda, que sobrevive com um salário mí

### Analizando o prompt

- Conclusão: o ChatGPT não utilizou o limite de tokens e escreveu Petições "pequenas"
- A seção DO DIREITO foi preterida em relação à seção DOS FATOS
- Os exemplos usados aqui são da modelo GPT3 (`gpt-3.5-turbo`)

### Comparando os modelos GPT3 e GPT4

- Abaixo, segue a Petição Inicial gerada utilizando o prompt anterior no modelo GPT4:

**Prompt**: 

```
Prepare uma petição inicial para o pagamento de pensão alimentícia. 
Leve em consideração as seguintes informações: 
- A petição será encaminhada para a Vara da Família do TJSP.  
- A solicitante é uma mulher divorciada cuja renda é de um salário mínimo. - A solicitante tem um filho menor com deficiência física. - Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia. - Atue como um advogado especializado em Direito da Família. 
- Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e a condição de pessoa com deficiência do seu filho. - Na seção intitulada "DOS FATOS" da Petição Inicial, seja bem detalhista, criativo e narre de forma ampla a situação. - Na seção intitulada "DOS FATOS" da Petição Inicial, use 200 palavras. - Para elaborar a Petição Inicial, use 2000 tokens. 
```

**Saída**:

```
Excelentíssimo Senhor Doutor Juiz de Direito da Vara da Família do Tribunal de Justiça do Estado de São Paulo

Processo nº: [número a ser atribuído pelo cartório]

FULANA DE TAL, brasileira, divorciada, profissão, portadora da carteira de identidade nº [número da identidade], inscrita no CPF sob o nº [número do CPF], residente e domiciliada na [endereço completo], vem, respeitosamente, perante Vossa Excelência, por meio de seu advogado infra-assinado, com fulcro no art. 1.694 do Código Civil e demais legislação aplicável, propor a presente

AÇÃO DE ALIMENTOS

em face de BELTRANO DE TAL, brasileiro, [estado civil], profissão, portador da carteira de identidade nº [número da identidade], inscrito no CPF sob o nº [número do CPF], residente e domiciliado na [endereço completo], pelos fatos e fundamentos que passa a expor:

I – DOS FATOS

A requerente e o requerido contraíram matrimônio em [data do casamento], do qual nasceu um único filho, CICLANO DE TAL, atualmente com [idade] anos de idade, portador de deficiência física, demandando cuidados especiais e tratamentos contínuos.

Durante o casamento, a requerente dedicou-se exclusivamente aos cuidados do lar e do filho, enquanto o requerido era o único provedor da família. Todavia, após o divórcio, o requerido tem se esquivado de suas responsabilidades paternas, deixando a requerente e o filho à mercê da própria sorte.

Atualmente, a requerente possui uma renda de apenas um salário mínimo, insuficiente para arcar com as despesas ordinárias e extraordinárias decorrentes do cuidado do filho, tais como: educação, saúde, alimentação, vestuário, transporte, lazer e demais necessidades inerentes à condição de pessoa com deficiência.

Por outro lado, o requerido ostenta um salário de R$ 5.000,00 (cinco mil reais) mensais, sendo plenamente capaz de arcar com a pensão alimentícia, a fim de garantir a dignidade e o bem-estar do filho. No entanto, nunca efetuou qualquer pagamento a título de pensão alimentícia, mesmo sendo instado extrajudicialmente.

Dessa forma, resta evidente o descaso do requerido para com o filho menor e a inobservância dos deveres inerentes à paternidade, causando um profundo desequilíbrio emocional e financeiro na vida da requerente e do filho.

II – DO DIREITO

O dever de prestar alimentos é decorrente do parentesco e tem como escopo garantir a subsistência e a dignidade daquele que os pleiteia, conforme previsão legal contida no art. 1.694 do Código Civil.

No presente caso, é indubitável a necessidade do filho menor em receber alimentos, bem como a capacidade do requerido em prestá-los, considerando sua situação financeira.

Em face do exposto, e com fundamento no princípio da solidariedade familiar, o valor da pensão alimentícia deve ser fixado de maneira proporcional às necessidades do alimentando e às possibilidades do alimentante, nos termos do art. 1.694, § 1º, do Código Civil.

Nesse sentido, é imperioso considerar as peculiaridades do caso, especialmente a condição de pessoa com deficiência do filho menor e a renda da requerente, insuficiente para prover todas as necessidades dele.

A jurisprudência do Tribunal de Justiça do Estado de São Paulo já se manifestou no sentido de que a pensão alimentícia deve ser fixada levando em consideração a capacidade financeira do alimentante e as necessidades do alimentando:

"[...] ALIMENTOS. Fixação. Observância dos critérios da necessidade, possibilidade e proporcionalidade. Precedentes desta Corte. Recurso não provido. [...] (TJSP; Apelação Cível 1005895-02.2019.8.26.0001; Relator (a): Des. José Rubens Queiroz Gomes; Órgão Julgador: 7ª Câmara de Direito Privado; Foro Central Cível - 1ª Vara da Família e Sucessões; Data do Julgamento: 25/02/2020; Data de Registro: 25/02/2020)"

Dessa forma, é fundamental a fixação de pensão alimentícia em valor condizente com as necessidades do filho e as possibilidades do requerido, a fim de garantir o mínimo existencial, o bem-estar e a dignidade do menor.

III - DOS PEDIDOS

Diante do exposto, requer a Vossa Excelência:

    A citação do requerido, para que, no prazo legal, conteste a presente ação, sob pena de revelia e confissão quanto à matéria de fato, nos termos do art. 344 do Código de Processo Civil;

    A procedência do pedido, condenando o requerido a pagar pensão alimentícia mensal em favor do filho menor, em valor a ser fixado por este Juízo, considerando as necessidades do alimentando e as possibilidades do alimentante, nos termos do art. 1.694, § 1º, do Código Civil;

    A fixação de alimentos provisórios, em valor a ser estabelecido por este Juízo, a serem pagos pelo requerido desde a citação, nos termos do art. 4º da Lei nº 5.478/68;

    A concessão dos benefícios da justiça gratuita à requerente, por ser pessoa comprovadamente pobre na forma da lei, conforme declaração de hipossuficiência anexa.

Dá-se à causa o valor de R$ [valor atribuído à causa].

Nestes termos,
Pede deferimento.

[local], [data].

[advogado]
OAB/SP nº [número de inscrição na OAB]
```


### Analizando o prompt

- Uma sugestão é dividir o problema em subproblemas


In [57]:
prompt = f"""
Preapre uma parte de uma petição inicial para o pagamento de pensão alimentícia. \

Leve em consideração as seguintes informações: \

- A parte que você vai elaborar é a seção "DOS FATOS". \
- A petição será encaminhada para a Vara da Família do TJSP. \ 
- A solicitante é uma mulher divorciada cuja renda é de um salário mínimo. \
- A solicitante tem um filho menor com deficiência física. \
- Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia. \
- Atue como um advogado especializado em Direito da Família. \
- Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e \
a condição de pessoa com deficiência do seu filho. \
Seja bem detalhista, criativo e narre de forma ampla a situação. \
"""

print_prompt_answer(prompt)

### Prompt


Preapre uma parte de uma petição inicial para o pagamento de pensão alimentícia. 
Leve em consideração as seguintes informações: 
- A parte que você vai elaborar é a seção "DOS FATOS". - A petição será encaminhada para a Vara da Família do TJSP. \ 
- A solicitante é uma mulher divorciada cuja renda é de um salário mínimo. - A solicitante tem um filho menor com deficiência física. - Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia. - Atue como um advogado especializado em Direito da Família. - Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e a condição de pessoa com deficiência do seu filho. Seja bem detalhista, criativo e narre de forma ampla a situação. 


### Resposta

EXCELENTÍSSIMO SENHOR JUIZ DE DIREITO DA VARA DA FAMÍLIA DO TRIBUNAL DE JUSTIÇA DO ESTADO DE SÃO PAULO.

NOME DA SOLICITANTE, brasileira, divorciada, portadora do RG nº XXXXXXXX e do CPF nº XXXXXXXX, residente e domiciliada na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, Cidade XXXXXXXX, Estado XXXXXXXX, por intermédio de seu advogado, vem, respeitosamente, à presença de Vossa Excelência, propor a presente AÇÃO DE ALIMENTOS em face de NOME DO REQUERIDO, brasileiro, portador do RG nº XXXXXXXX e do CPF nº XXXXXXXX, residente e domiciliado na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, Cidade XXXXXXXX, Estado XXXXXXXX, pelos motivos de fato e de direito a seguir expostos:

DOS FATOS

A requerente é mãe de um filho menor, com deficiência física, que necessita de cuidados especiais e tratamentos médicos constantes. A requerente é divorciada e possui renda mensal de apenas um salário mínimo, o que torna difícil a manutenção das despesas básicas do lar e do tratamento do filho.

O requerido, por sua vez, é pai do menor e possui renda mensal de R$ 5.000,00, conforme comprovado por meio de documentos anexos. No entanto, nunca pagou a pensão alimentícia devida ao filho, deixando a requerente em situação de extrema dificuldade financeira.

A situação da requerente e do filho é extremamente delicada, tendo em vista a condição de saúde do menor e a falta de recursos financeiros para arcar com as despesas necessárias. A requerente tem se esforçado ao máximo para garantir o bem-estar do filho, mas sem a contribuição do requerido, a situação tem se tornado insustentável.

Diante do exposto, a requerente solicita a Vossa Excelência que determine o pagamento de pensão alimentícia em favor do filho menor, no valor correspondente a 30% dos rendimentos do requerido, conforme previsto em lei.

A requerente reitera que a situação é urgente e que a falta de recursos financeiros tem prejudicado o tratamento e a qualidade de vida do filho. Por isso, apela para a sensibilidade de Vossa Excelência para que a presente ação seja julgada procedente, garantindo assim o direito do menor à pensão alimentícia.

DOS PEDIDOS

Diante do exposto, requer a Vossa Excelência:

a) A citação do requerido para que, querendo, apresente resposta à presente ação;

b) A procedência da presente ação, com a determinação do pagamento de pensão alimentícia em favor do filho menor, no valor correspondente a 30% dos rendimentos do requerido;

c) A condenação do requerido ao pagamento das custas processuais e honorários advocatícios.

Protesta provar o alegado por todos os meios de prova em direito admitidos, especialmente pela juntada de documentos, depoimento pessoal do requerido, oitiva de testemunhas e demais provas que se fizerem necessárias.

Dá-se à causa o valor de R$ XXXXXXXX.

Termos em que,

Pede deferimento.

Local, data.

Advogado

OAB/XX nº XXXXXXXX

EXCELENTÍSSIMO SENHOR JUIZ DE DIREITO DA VARA DA FAMÍLIA DO TRIBUNAL DE JUSTIÇA DO ESTADO DE SÃO PAULO.

NOME DA SOLICITANTE, brasileira, divorciada, portadora do RG nº XXXXXXXX e do CPF nº XXXXXXXX, residente e domiciliada na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, Cidade XXXXXXXX, Estado XXXXXXXX, por intermédio de seu advogado, vem, respeitosamente, à presença de Vossa Excelência, propor a presente AÇÃO DE ALIMENTOS em face de NOME DO REQUERIDO, brasileiro, portador do RG nº XXXXXXXX e do CPF nº XXXXXXXX, residente e domiciliado na Rua XXXXXXXX, nº XX, Bairro XXXXXXXX, Cidade XXXXXXXX, Estado XXXXXXXX, pelos motivos de fato e de direito a seguir expostos:

DOS FATOS

A requerente é mãe de um filho menor, com deficiência física, que necessita de cuidados especiais e tratamentos médicos constantes. A requerente é divorciada e possui renda mensal de apenas um salário mínimo, o que torna difícil a manutenção das despesas básicas do lar e do tratamento do filho.

O requerido, por sua vez, 

### Analizando o prompt

- Faltou especificidade, vamos ser mais precisos:

In [58]:
prompt = f"""
Preapre a seção "DOS FATOS" de uma petição inicial para o pagamento de pensão alimentícia. \

Leve em consideração as seguintes informações: \

- A petição será encaminhada para a Vara da Família do TJSP. \ 
- A solicitante é uma mulher divorciada cuja renda é de um salário mínimo. \
- A solicitante tem um filho menor com deficiência física. \
- Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia. \
- Atue como um advogado especializado em Direito da Família. \
- Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e \
a condição de pessoa com deficiência do seu filho. \
Seja bem detalhista, criativo e narre de forma ampla a situação. \
"""

print_prompt_answer(prompt)

### Prompt


Preapre a seção "DOS FATOS" de uma petição inicial para o pagamento de pensão alimentícia. 
Leve em consideração as seguintes informações: 
- A petição será encaminhada para a Vara da Família do TJSP. \ 
- A solicitante é uma mulher divorciada cuja renda é de um salário mínimo. - A solicitante tem um filho menor com deficiência física. - Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia. - Atue como um advogado especializado em Direito da Família. - Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e a condição de pessoa com deficiência do seu filho. Seja bem detalhista, criativo e narre de forma ampla a situação. 


### Resposta

DOS FATOS

A requerente é uma mulher divorciada, cuja renda mensal é de um salário mínimo, e tem um filho menor com deficiência física. O requerido, por sua vez, é o pai da criança e possui renda mensal de R$ 5.000,00.

Desde a separação, o requerido nunca pagou a pensão alimentícia devida ao filho, o que tem gerado grande dificuldade financeira para a requerente, que tem que arcar sozinha com todas as despesas do filho, incluindo as relacionadas à sua deficiência.

A situação financeira da requerente é extremamente precária, tendo em vista que ela não possui outras fontes de renda além do salário mínimo que recebe. Além disso, a condição de pessoa com deficiência do filho exige gastos extras com tratamentos médicos, fisioterapia, medicamentos, entre outros.

Diante disso, a requerente vem por meio desta petição requerer o pagamento da pensão alimentícia devida pelo requerido, a fim de garantir a subsistência do filho e suprir as necessidades básicas da família.

Ressalta-se que a situação de vulnerabilidade da requerente e do filho é agravada pela ausência de pagamento da pensão alimentícia, o que tem gerado grande angústia e sofrimento para ambos.

Assim, espera-se que este Juízo possa sensibilizar-se com a situação da requerente e do filho, e determinar o pagamento da pensão alimentícia devida pelo requerido, a fim de garantir a dignidade e o bem-estar da família.

DOS FATOS

A requerente é uma mulher divorciada, cuja renda mensal é de um salário mínimo, e tem um filho menor com deficiência física. O requerido, por sua vez, é o pai da criança e possui renda mensal de R$ 5.000,00.

Desde a separação, o requerido nunca pagou a pensão alimentícia devida ao filho, o que tem gerado grande dificuldade financeira para a requerente, que tem que arcar sozinha com todas as despesas do filho, incluindo as relacionadas à sua deficiência.

A situação financeira da requerente é extremamente precária, tendo em vista que ela não possui outras fontes de renda além do salário mínimo que recebe. Além disso, a condição de pessoa com deficiência do filho exige gastos extras com tratamentos médicos, fisioterapia, medicamentos, entre outros.

Diante disso, a requerente vem por meio desta petição requerer o pagamento da pensão alimentícia devida pelo requerido, a fim de garantir a subsistência do filho e suprir as necessidades básicas da família.

Ressalta-se que a situ

### Analizando o prompt

- Ficou melhor!
- Vamos agora automatizar a criação das demais seções da Petição Inicial

In [59]:
# vetor com os nomes das seções
secoes = [ "DOS FATOS", "DO DIREITO", "DOS PEDIDOS" ]

# iteração para cada seção
for secao in secoes:
    prompt = f"""
    Preapre a seção "{secao}" de uma petição inicial para o pagamento de pensão alimentícia. \

    Leve em consideração as seguintes informações: \

    - A petição será encaminhada para a Vara da Família do TJSP. \ 
    - A solicitante é uma mulher divorciada cuja renda é de um salário mínimo. \
    - A solicitante tem um filho menor com deficiência física. \
    - Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia. \
    - Atue como um advogado especializado em Direito da Família. \
    - Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e \
    a condição de pessoa com deficiência do seu filho. \
    Seja bem detalhista, criativo e narre de forma ampla a situação. \
    """
    print_prompt_answer(prompt)

### Prompt


    Preapre a seção "DOS FATOS" de uma petição inicial para o pagamento de pensão alimentícia. 
    Leve em consideração as seguintes informações: 
    - A petição será encaminhada para a Vara da Família do TJSP. \ 
    - A solicitante é uma mulher divorciada cuja renda é de um salário mínimo.     - A solicitante tem um filho menor com deficiência física.     - Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia.     - Atue como um advogado especializado em Direito da Família.     - Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e     a condição de pessoa com deficiência do seu filho.     Seja bem detalhista, criativo e narre de forma ampla a situação.     


### Resposta

DOS FATOS

A requerente é uma mulher divorciada, de nome fictício Maria, que atualmente possui uma renda mensal de um salário mínimo. Maria é mãe de um filho menor, de nome fictício João, que possui deficiência física e necessita de cuidados especiais.

O requerido, de nome fictício José, é o pai de João e possui um salário mensal de R$ 5.000,00. Desde a separação, José nunca pagou a pensão alimentícia devida ao filho, o que tem gerado grande dificuldade financeira para Maria e João.

A situação de Maria e João é extremamente delicada, uma vez que a renda da mãe é insuficiente para arcar com todas as despesas necessárias para o sustento do filho, especialmente considerando a condição de deficiência física de João, que demanda cuidados especiais e tratamentos médicos frequentes.

Diante disso, a requerente vem por meio desta petição solicitar ao Juízo da Vara da Família do TJSP que determine o pagamento da pensão alimentícia devida por José, de forma a garantir o sustento e bem-estar de João.

A situação de Maria e João é extremamente sensível e requer a atenção e sensibilidade deste Juízo. A requerente apela para a compreensão e solidariedade do Juízo, enfatizando a renda limitada da mãe e a condição de pessoa com deficiência do seu filho, que necessita de cuidados especiais e tratamentos médicos frequentes.

Assim, a requerente espera que este Juízo possa acolher o seu pedido e determinar o pagamento da pensão alimentícia devida por José, de forma a garantir o sustento e bem-estar de João.

DOS FATOS

A requerente é uma mulher divorciada, de nome fictício Maria, que atualmente possui uma renda mensal de um salário mínimo. Maria é mãe de um filho menor, de nome fictício João, que possui deficiência física e necessita de cuidados especiais.

O requerido, de nome fictício José, é o pai de João e possui um salário mensal de R$ 5.000,00. Desde a separação, José nunca pagou a pensão alimentícia devida ao filho, o que tem gerado grande dificuldade financeira para Maria e João.

A situação de Maria e João é extremamente delicada, uma vez que a renda da mãe é insuficiente para arcar com todas as despesas necessárias para o sustento do filho, especialmente considerando a condição de deficiência física de João, que demanda cuidados especiais e tratamentos médicos frequentes.

Diante disso, a requerente vem por meio desta petição solicitar ao Juízo da Vara da Família do TJSP que determine o pagamento da pensão alimentícia devida por José, de forma a garantir o sustento e bem-estar de

### Prompt


    Preapre a seção "DO DIREITO" de uma petição inicial para o pagamento de pensão alimentícia. 
    Leve em consideração as seguintes informações: 
    - A petição será encaminhada para a Vara da Família do TJSP. \ 
    - A solicitante é uma mulher divorciada cuja renda é de um salário mínimo.     - A solicitante tem um filho menor com deficiência física.     - Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia.     - Atue como um advogado especializado em Direito da Família.     - Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e     a condição de pessoa com deficiência do seu filho.     Seja bem detalhista, criativo e narre de forma ampla a situação.     


### Resposta

DO DIREITO

A presente ação tem como objetivo o pagamento de pensão alimentícia em favor do filho menor da requerente, que possui deficiência física, em razão da ausência de pagamento por parte do requerido.

Conforme preceitua o artigo 1.694 do Código Civil, os pais têm o dever de assistir, criar e educar os filhos menores, cabendo-lhes ainda a obrigação de prover-lhes o sustento, inclusive alimentação, vestuário, moradia e educação.

No caso em tela, a requerente é uma mulher divorciada, cuja renda é de apenas um salário mínimo, o que torna inviável a manutenção do filho menor sem a contribuição do requerido. Além disso, o filho da requerente possui deficiência física, o que demanda gastos extras com tratamentos e medicamentos.

O requerido, por sua vez, possui renda mensal de R$ 5.000,00 e nunca pagou a pensão alimentícia devida ao filho menor. Tal conduta configura violação ao dever de sustento e assistência previsto em lei, bem como demonstra total desrespeito à situação de vulnerabilidade da requerente e do filho.

Diante do exposto, requer-se a fixação de pensão alimentícia em favor do filho menor da requerente, no valor correspondente a 30% dos rendimentos do requerido, a ser depositada mensalmente em conta bancária indicada pela requerente.

Ressalta-se que a fixação da pensão alimentícia é medida urgente e necessária para garantir a subsistência do filho menor da requerente, bem como para assegurar o seu direito à dignidade e à vida.

Por fim, apela-se à sensibilidade deste Juízo para que, ao analisar o presente pedido, leve em consideração a renda da requerente e a condição de pessoa com deficiência do seu filho, a fim de garantir a justiça e a equidade na presente demanda.

Nestes termos, pede deferimento.

(Local, data e assinatura do advogado)

DO DIREITO

A presente ação tem como objetivo o pagamento de pensão alimentícia em favor do filho menor da requerente, que possui deficiência física, em razão da ausência de pagamento por parte do requerido.

Conforme preceitua o artigo 1.694 do Código Civil, os pais têm o dever de assistir, criar e educar os filhos menores, cabendo-lhes ainda a obrigação de prover-lhes o sustento, inclusive alimentação, vestuário, moradia e educação.

No caso em tela, a requerente é uma mulher divorciada, cuja renda é de apenas um salário mínimo, o que torna inviável a manutenção do filho menor sem a contribuição do requerido. Além disso, o filho da requerente possui deficiência física, o que demanda gastos extras com tratamentos e medicamentos.

O requerido, por sua vez, possui renda mensal de R$ 5.000,00 e nunca pagou a pensão alimentícia devida ao filho menor. Tal conduta configura violação ao dever de sustento e assistência previsto em lei, bem como demonstra total desrespeito à situação de vulner

### Prompt


    Preapre a seção "DOS PEDIDOS" de uma petição inicial para o pagamento de pensão alimentícia. 
    Leve em consideração as seguintes informações: 
    - A petição será encaminhada para a Vara da Família do TJSP. \ 
    - A solicitante é uma mulher divorciada cuja renda é de um salário mínimo.     - A solicitante tem um filho menor com deficiência física.     - Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia.     - Atue como um advogado especializado em Direito da Família.     - Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e     a condição de pessoa com deficiência do seu filho.     Seja bem detalhista, criativo e narre de forma ampla a situação.     


### Resposta

DOS PEDIDOS

Diante do exposto, requer-se a Vossa Excelência:

1. A concessão de tutela de urgência, nos termos do artigo 300 do Código de Processo Civil, para que o requerido seja imediatamente compelido a pagar a pensão alimentícia no valor de 30% do seu salário, correspondente a R$ 1.500,00 (mil e quinhentos reais), em favor do filho menor com deficiência física da requerente, a partir da citação, sob pena de multa diária no valor de R$ 100,00 (cem reais) em caso de descumprimento.

2. A fixação definitiva da pensão alimentícia no valor de 30% do salário do requerido, correspondente a R$ 1.500,00 (mil e quinhentos reais), em favor do filho menor com deficiência física da requerente, a ser paga mensalmente até que o mesmo complete 18 anos de idade ou até que cesse a necessidade, nos termos do artigo 1.694 do Código Civil.

3. A condenação do requerido ao pagamento das parcelas vencidas e não pagas desde a data da separação, acrescidas de juros e correção monetária, nos termos do artigo 528, § 1º, do Código de Processo Civil.

4. A condenação do requerido ao pagamento das despesas processuais e honorários advocatícios, nos termos do artigo 85, § 1º, do Código de Processo Civil.

Requer-se, ainda, a produção de todas as provas admitidas em direito, em especial a documental, testemunhal e pericial, para a comprovação dos fatos alegados.

Termos em que, pede deferimento.

(Local e data)

(Nome e assinatura do advogado)

DOS PEDIDOS

Diante do exposto, requer-se a Vossa Excelência:

1. A concessão de tutela de urgência, nos termos do artigo 300 do Código de Processo Civil, para que o requerido seja imediatamente compelido a pagar a pensão alimentícia no valor de 30% do seu salário, correspondente a R$ 1.500,00 (mil e quinhentos reais), em favor do filho menor com deficiência física da requerente, a partir da citação, sob pena de multa diária no valor de R$ 100,00 (cem reais) em caso de descumprimento.

2. A fixação definitiva da pensão alimentícia no valor de 30% do salário do requerido, correspondente a R$ 1.500,00 (mil e quinhentos reais), em favor do filho menor com deficiência física da requerente, a ser paga mensalmente até que o mesmo complete 18 anos de idade ou até que cesse a necessidade, nos termos do artigo 1.694 do Código Civil.

3. A condenação do requerido ao pagamento das parcelas vencidas e não pagas desde a data da separação, acrescidas de juros e correção monetária, nos termos do arti

### Analizando prompt

- Ficou melhor
- Vamos tentar melhorar ainda mais pedindo para citar leis, etc. porque na seção DO DIREITO citou apenas o Código Civil

In [60]:
# vetor com os nomes das seções
secoes = [ "DOS FATOS", "DO DIREITO", "DOS PEDIDOS" ]

# iteração para cada seção
for secao in secoes:
    prompt = f"""
    Preapre a seção "{secao}" de uma petição inicial para o pagamento de pensão alimentícia. \

    Leve em consideração as seguintes informações: \

    - A petição será encaminhada para a Vara da Família do TJSP. \ 
    - A solicitante é uma mulher divorciada cuja renda é de um salário mínimo. \
    - A solicitante tem um filho menor com deficiência física. \
    - Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia. \
    - Atue como um advogado especializado em Direito da Família. \
    - Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e \
    a condição de pessoa com deficiência do seu filho. \
    Seja bem detalhista, criativo e narre de forma ampla a situação. \
    
    - Cite as normas jurídicas relativas ao pagamento de pensão alimentícia. \
    """
    print_prompt_answer(prompt)

### Prompt


    Preapre a seção "DOS FATOS" de uma petição inicial para o pagamento de pensão alimentícia. 
    Leve em consideração as seguintes informações: 
    - A petição será encaminhada para a Vara da Família do TJSP. \ 
    - A solicitante é uma mulher divorciada cuja renda é de um salário mínimo.     - A solicitante tem um filho menor com deficiência física.     - Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia.     - Atue como um advogado especializado em Direito da Família.     - Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e     a condição de pessoa com deficiência do seu filho.     Seja bem detalhista, criativo e narre de forma ampla a situação.     
    - Cite as normas jurídicas relativas ao pagamento de pensão alimentícia.     


### Resposta

DOS FATOS

A requerente é uma mulher divorciada, cuja renda mensal é de um salário mínimo, e tem a guarda de seu filho menor, que possui deficiência física. O requerido, por sua vez, é o pai da criança e possui renda mensal de R$ 5.000,00.

Desde a separação, o requerido nunca pagou a pensão alimentícia devida ao filho, o que tem gerado grande dificuldade financeira para a requerente, que tem que arcar sozinha com todas as despesas do filho, incluindo as relacionadas à sua deficiência.

A situação é ainda mais grave considerando que a requerente não tem condições financeiras de arcar com as despesas médicas e terapêuticas necessárias para o tratamento do filho, o que tem prejudicado o seu desenvolvimento e qualidade de vida.

Diante disso, a requerente vem por meio desta petição requerer o pagamento da pensão alimentícia devida pelo requerido, nos termos do artigo 1.694 do Código Civil, que estabelece a obrigação dos pais de prover o sustento dos filhos.

Além disso, a Lei nº 13.146/2015, que institui a Lei Brasileira de Inclusão da Pessoa com Deficiência, estabelece em seu artigo 84 que a pessoa com deficiência tem direito à proteção à vida, à saúde e à assistência social, o que inclui o direito à pensão alimentícia para garantir o seu sustento e tratamento adequado.

Assim, a requerente solicita que o requerido seja compelido a pagar a pensão alimentícia devida ao filho, levando em consideração a sua condição de pessoa com deficiência e as dificuldades financeiras enfrentadas pela requerente para arcar com as despesas necessárias ao seu tratamento e desenvolvimento.

DOS FATOS

A requerente é uma mulher divorciada, cuja renda mensal é de um salário mínimo, e tem a guarda de seu filho menor, que possui deficiência física. O requerido, por sua vez, é o pai da criança e possui renda mensal de R$ 5.000,00.

Desde a separação, o requerido nunca pagou a pensão alimentícia devida ao filho, o que tem gerado grande dificuldade financeira para a requerente, que tem que arcar sozinha com todas as despesas do filho, incluindo as relacionadas à sua deficiência.

A situação é ainda mais grave considerando que a requerente não tem condições financeiras de arcar com as despesas médicas e terapêuticas necessárias para o tratamento do filho, o que tem prejudicado o seu desenvolvimento e qualidade de vida.

Diante disso, a requerente vem por meio desta petição requerer o pagamento da pensão alimentícia devida pelo requerido, nos termos do artigo 1.694 do Código Civil, que estabelece a obrigação dos pais de prover o sustento dos filhos.

Além disso, a Lei nº 13.146/20

### Prompt


    Preapre a seção "DO DIREITO" de uma petição inicial para o pagamento de pensão alimentícia. 
    Leve em consideração as seguintes informações: 
    - A petição será encaminhada para a Vara da Família do TJSP. \ 
    - A solicitante é uma mulher divorciada cuja renda é de um salário mínimo.     - A solicitante tem um filho menor com deficiência física.     - Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia.     - Atue como um advogado especializado em Direito da Família.     - Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e     a condição de pessoa com deficiência do seu filho.     Seja bem detalhista, criativo e narre de forma ampla a situação.     
    - Cite as normas jurídicas relativas ao pagamento de pensão alimentícia.     


### Resposta

DO DIREITO

A presente ação tem como fundamento o direito à pensão alimentícia, previsto no artigo 1.694 do Código Civil, que estabelece a obrigação de prestar alimentos aos filhos, aos ascendentes e ao cônjuge, sempre que quem os pretenda não tiver bens suficientes, nem poder laboral para o seu próprio sustento.

No caso em questão, a requerente é uma mulher divorciada, cuja renda é de um salário mínimo, e que tem um filho menor com deficiência física. O requerido, por sua vez, possui renda mensal de R$ 5.000,00 e nunca pagou a pensão alimentícia.

A obrigação de prestar alimentos é recíproca entre pais e filhos, e deve ser fixada levando-se em consideração as necessidades do alimentando e as possibilidades do alimentante, conforme estabelece o artigo 1.695 do Código Civil.

No caso em questão, a requerente não possui condições financeiras para arcar com as despesas do filho, que necessita de cuidados especiais em razão de sua deficiência física. Por outro lado, o requerido possui renda suficiente para arcar com a pensão alimentícia, mas nunca cumpriu com essa obrigação.

Além disso, a Constituição Federal de 1988, em seu artigo 227, estabelece que é dever da família, da sociedade e do Estado assegurar à criança e ao adolescente, com absoluta prioridade, o direito à vida, à saúde, à alimentação, à educação, ao lazer, à profissionalização, à cultura, à dignidade, ao respeito, à liberdade e à convivência familiar e comunitária.

Nesse sentido, é imprescindível que o requerido cumpra com sua obrigação de prestar alimentos ao filho, garantindo-lhe condições dignas de vida e de desenvolvimento.

Diante do exposto, requer-se a fixação de pensão alimentícia em favor do filho menor com deficiência física da requerente, no valor correspondente a 30% dos rendimentos líquidos do requerido, a serem depositados mensalmente em conta bancária indicada pela requerente, sob pena de multa diária em caso de descumprimento.

DO DIREITO

A presente ação tem como fundamento o direito à pensão alimentícia, previsto no artigo 1.694 do Código Civil, que estabelece a obrigação de prestar alimentos aos filhos, aos ascendentes e ao cônjuge, sempre que quem os pretenda não tiver bens suficientes, nem poder laboral para o seu próprio sustento.

No caso em questão, a requerente é uma mulher divorciada, cuja renda é de um salário mínimo, e que tem um filho menor com deficiência física. O requerido, por sua vez, possui renda mensal de R$ 5.000,00 e nunca pagou a pensão alimentícia.

A obrigação de prestar alimentos é recíproca entre pais e filhos, e deve ser fixada levando-se em consideração as necessidades do alimentando e as possibilidades do alimentante, conforme estabelece o artigo 1.695 do Código Civil.

No caso em questão, a requerente não possui condições financeiras para arcar com as despesas do filho, que necessita de cuidados especiais em razão de sua deficiência física. Por outro lado, o requerido possui ren

### Prompt


    Preapre a seção "DOS PEDIDOS" de uma petição inicial para o pagamento de pensão alimentícia. 
    Leve em consideração as seguintes informações: 
    - A petição será encaminhada para a Vara da Família do TJSP. \ 
    - A solicitante é uma mulher divorciada cuja renda é de um salário mínimo.     - A solicitante tem um filho menor com deficiência física.     - Saiba que o salário do pai é de R$ 5.000 e ele nunca pagou a pensão alimentícia.     - Atue como um advogado especializado em Direito da Família.     - Use um tom apelativo para sensibilizar o juiz, enfatizando a renda da mãe e     a condição de pessoa com deficiência do seu filho.     Seja bem detalhista, criativo e narre de forma ampla a situação.     
    - Cite as normas jurídicas relativas ao pagamento de pensão alimentícia.     


### Resposta

DOS PEDIDOS

Diante do exposto, requer-se a Vossa Excelência:

1. A concessão de tutela de urgência para determinar ao requerido o pagamento imediato da pensão alimentícia em favor do filho menor com deficiência física, no valor correspondente a 30% do seu salário, conforme previsão legal.

2. A fixação definitiva da pensão alimentícia em favor do filho menor com deficiência física, no valor correspondente a 30% do salário do requerido, a ser depositado mensalmente na conta bancária indicada pela requerente.

3. A condenação do requerido ao pagamento das parcelas vencidas e não pagas da pensão alimentícia, desde a data da separação do casal, acrescidas de juros e correção monetária.

4. A aplicação de multa diária em caso de descumprimento da ordem judicial, nos termos do artigo 528, §4º, do Código de Processo Civil.

5. A condenação do requerido ao pagamento das custas processuais e honorários advocatícios, nos termos do artigo 85, §2º, do Código de Processo Civil.

Fundamentação jurídica:

O direito à pensão alimentícia está previsto no artigo 1.694 do Código Civil, que dispõe que "podem os parentes, os cônjuges ou companheiros pedir uns aos outros os alimentos de que necessitem para viver de modo compatível com a sua condição social, inclusive para atender às necessidades de sua educação". Além disso, o artigo 1.695 do mesmo diploma legal estabelece que "são devidos os alimentos quando quem os pretende não tem bens suficientes, nem pode prover, pelo seu trabalho, à própria mantença, e aquele, de quem se reclamam, pode fornecê-los, sem desfalque do necessário ao seu sustento".

No caso em tela, a requerente é uma mulher divorciada cuja renda é de um salário mínimo, não tendo condições financeiras de prover a subsistência do filho menor com deficiência física. Por outro lado, o requerido possui renda mensal de R$ 5.000,00 e nunca pagou a pensão alimentícia devida ao filho.

Assim, considerando a necessidade do filho menor com deficiência física e a capacidade financeira do requerido, é imperativo que seja fixada a pensão alimentícia em favor do menor, nos termos requeridos.

Por fim, ressalta-se que a situação narrada é de extrema sensibilidade, envolvendo a subsistência de uma criança com deficiência física e a dificuldade financeira da mãe. Nesse sentido, espera-se que Vossa Excelência, sensibilizado com a situação, conceda a tutela de urgência requerida e julgue procedente o pedido de fixação da pensão alimentícia em favor do menor.

Termos em que,

Pede deferimento.

(Local e data)

(Nome e assinatura do advogado)

DOS PEDIDOS

Diante do exposto, requer-se a Vossa Excelência:

1. A concessão de tutela de urgência para determinar ao requerido o pagamento imediato da pensão alimentícia em favor do filho menor com deficiência física, no valor correspondente a 30% do seu salário, conforme previsão legal.

2. A fixação definitiva da pensão alimentícia em favor do filho menor com deficiência física, no valor correspondente a 30% do salário do requerido, a ser depositado mensalmente na conta bancária indicada pela requerente.

3. A condenação do requerido ao pagamento das parcelas vencidas e não pagas da pensão alimentícia, desde a data da separação do casal, acrescidas de juros e correção monetária.

4. A aplicação de multa diária em caso de descumprimento da ordem judicial, nos termos do artigo 528, §4º, do Código de Processo Civil.

5. A condenação do requerido ao pagamento das custas processuais e honorários advocatícios, nos termos do artigo 85, §2º, do Código de Processo Civil.

Fundamentação jurí

### Analizando o prompt

- **Conclusões para esse estudo de caso**
  - O modelo GPT3 tendou a utilizar poucos tokens nas suas respostas 
  - Separando o problema em subproblemas menores produziu resultados de maior qualidade
  
### Sua vez :-)

1. Investigue se as normas jurídicas foram citadas corretamente
2. Elabore outro tipo de petição adaptando os prompts para o caso escolhido